'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {unzipSync,strFromU8}=require('fflate');const {XMLParser}=require('fast-xml-parser');const F=require('./finance.cjs');
const arr=x=>x===undefined?[]:Array.isArray(x)?x:[x];
const norm=x=>String(x??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function readXlsx(bytes){
 if(bytes.length>30*1024*1024)throw Error('O limite de importação é 30 MB.');
 let total=0;const z=unzipSync(new Uint8Array(bytes),{filter:f=>{total+=f.originalSize;if(total>100*1024*1024)throw Error('Planilha descompactada acima de 100 MB.');return /\.xml$|\.rels$/.test(f.name)&&!f.name.includes('../');}});
 const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@',parseTagValue:false,trimValues:false,processEntities:true});
 const xml=name=>{if(!z[name])throw Error('Estrutura XLSX inválida: '+name);const text=strFromU8(z[name]);if(/<!DOCTYPE/i.test(text))throw Error('XML não suportado.');return parser.parse(text);};
 const text=x=>typeof x==='object'?(x?.['#text']??''):x??'';
 const rich=x=>x?.t!==undefined?text(x.t):arr(x?.r).map(r=>text(r.t)).join('');
 const strings=z['xl/sharedStrings.xml']?arr(xml('xl/sharedStrings.xml').sst?.si).map(rich):[];
 const wb=xml('xl/workbook.xml').workbook;if(wb.workbookPr?.['@date1904']==='1')throw Error('Calendário 1904 não suportado. Salve uma cópia no calendário 1900.');
 const rels=Object.fromEntries(arr(xml('xl/_rels/workbook.xml.rels').Relationships?.Relationship).map(r=>[r['@Id'],r['@Target']]));const sheets={};
 for(const sh of arr(wb.sheets?.sheet)){let target=rels[sh['@r:id']];if(!target)throw Error('Aba sem relação XLSX.');target=target.startsWith('/')?target.slice(1):path.posix.normalize('xl/'+target);if(!target.startsWith('xl/'))throw Error('Relação XLSX inválida.');const sheet=xml(target).worksheet,cells={};for(const row of arr(sheet.sheetData?.row))for(const c of arr(row.c)){const type=c['@t'],raw=text(c.v),f=c.f!==undefined?'='+text(c.f):undefined;let v=type==='s'?strings[Number(raw)]:type==='inlineStr'?rich(c.is):type==='b'?raw==='1':type==='str'?raw:raw!==''?Number(raw):undefined;if(type==='e')v=undefined;cells[c['@r']]={v,f,error:type==='e'?raw:undefined};}sheets[sh['@name']]={cells};}
 return {sheets};
}
function fromSnapshot(snapshot){const sheets={};for(const [name,sh]of Object.entries(snapshot.sheets||{})){const cells={};for(const [key,c]of Object.entries(sh.cells)){const e=c.effectiveValue||c.userEnteredValue||{};cells[key]={v:e.numberValue??e.stringValue??e.boolValue,f:c.userEnteredValue?.formulaValue,error:e.errorValue?.type};}sheets[name]={cells};}return {sheets};}
function excelDate(v){if(typeof v==='number'&&v>31)return new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000).toISOString().slice(0,10);if(F.validDate(v))return v;const m=String(v||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m){const out=`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return F.validDate(out)?out:null;}return null;}
function readFile(file){const bytes=fs.readFileSync(file);return {book:file.endsWith('.json')?fromSnapshot(JSON.parse(bytes.toString('utf8'))):readXlsx(bytes),hash:crypto.createHash('sha256').update(bytes).digest('hex'),name:path.basename(file)};}
function planImport(source,opts={}){
 const {book,hash,name}=source;const year=Number(opts.year);if(!Number.isInteger(year)||year<1900||year>2200)throw Error('Informe o ano dos lançamentos e aportes. Os títulos antigos não determinam o ano.');
 const records=[],warnings=[],issues=[],checks=[],settings={};const prefix='imp-'+hash.slice(0,12)+'-';let seq=0;const id=()=>prefix+(++seq);
 const sheet=n=>{if(!book.sheets[n])throw Error('Aba obrigatória ausente: '+n);return book.sheets[n].cells;};
 const v=(s,k)=>s[k]?.v;const get=(s,k)=>v(s,k)??'';const cash=(s,k)=>{const x=v(s,k);if(x===undefined||x===''){if(s[k]?.f)throw Error('Fórmula sem valor calculado em '+k+'. Abra e salve o XLSX no Excel/Sheets.');return 0;}return F.money(x);};
 const issue=(source,message,raw)=>issues.push({source,message,raw});const put=(kind,obj)=>{const r={id:id(),kind,...obj};records.push(r);return r;};
 const categories=new Map();function cat(name,type='despesa',group='Outros'){name=String(name).trim();const key=norm(name);if(categories.has(key))return categories.get(key);const r=put('category',{name,type,group,archived:false});categories.set(key,r);return r;}
 const budget=sheet('Orçamento');if(norm(get(budget,'A3'))!=='categorias'||norm(get(budget,'B3'))!=='janeiro')throw Error('Cabeçalhos do Orçamento mudaram; revisão de mapeamento necessária.');
 const blocks=[[5,16,'Receitas','receita'],[19,37,'Moradia','despesa'],[39,43,'Alimentação','despesa'],[45,57,'Transporte','despesa'],[59,70,'Saúde','despesa'],[75,82,'Cuidados Pessoais','despesa'],[84,90,'Lazer','despesa'],[92,98,'Educação','despesa'],[100,106,'Aquisições Pessoais','despesa'],[108,112,'Assinaturas','despesa'],[114,120,'PET','despesa'],[122,127,'Outros','despesa'],[132,138,'Metas Financeiras','investimento'],[146,153,'Cartões','despesa']];
 for(const [start,end,group,type]of blocks)for(let row=start;row<=end;row++){const label=get(budget,'A'+row);if(!label)continue;const kind=row===5?'saldo':row===132?'divida':group==='Cartões'&&opts.cardSource==='detailed'?'fatura':type;const c=cat(label,kind,group);for(let m=1;m<=12;m++){const key=String.fromCharCode(65+m)+row;try{const amount=cash(budget,key);if(amount>0)put('budget',{categoryId:c.id,period:`${year}-${String(m).padStart(2,'0')}`,amount,source:'Orçamento!'+key});}catch(e){issue('Orçamento!'+key,e.message,get(budget,key));}}}
 for(const [mi,name]of F.MONTHS.entries()){
 const s=sheet(name);if(norm(get(s,'G3'))!=='dia'||norm(get(s,'H3'))!=='entradas'||norm(get(s,'I3'))!=='saidas'||norm(get(s,'K3'))!=='valor')throw Error('Cabeçalhos de '+name+' mudaram; revisão necessária.');
 let income=0,out=0;for(let r=4;r<=498;r++){const cells=['G','H','I','J','K'].map(c=>get(s,c+r));if(cells.every(x=>x===''))continue;const [day,inc,exp,desc,amt]=cells;const source=name+'!G'+r+':K'+r;try{if((inc&&exp)||(!inc&&!exp))throw Error('Escolha entrada ou saída, com uma única categoria.');const category=cat(inc||exp,inc?'receita':'despesa');const amount=cash(s,'K'+r);if(amount<=0)throw Error('Valor precisa ser positivo.');let date=excelDate(day);if(!date&&Number.isInteger(Number(day))&&+day>=1&&+day<=31){date=F.date(year,mi+1,+day);if(+date.slice(8)!==+day)throw Error('Dia inexistente no mês.');}if(!date)throw Error('Data não definida.');if(+date.slice(5,7)!==mi+1)throw Error('Data pertence a outro mês.');put('entry',{date,description:String(desc||inc||exp),categoryId:category.id,type:category.type,amount,source});if(inc)income+=amount;else out+=amount;}catch(e){issue(source,e.message,cells);}}
 checks.push({sheet:name,sourceIncome:v(s,'D18')??0,importIncome:income/100,sourceOut:v(s,'D146')??0,importOut:out/100});
 for(let r=171;r<=Math.min(883,Math.max(...Object.keys(s).map(k=>+k.replace(/\D/g,''))));r++){if(!get(s,'D'+r)&&!get(s,'B'+r))continue;try{const category=cat(get(s,'C'+r));if(!category.name)throw Error('Categoria ausente.');const day=Number(get(s,'B'+r));const date=excelDate(get(s,'B'+r))||F.date(year,mi+1,day);put('bill',{name:category.name,categoryId:category.id,date,amount:cash(s,'D'+r),paid:norm(get(s,'E'+r)).includes('pago'),source:name+'!B'+r+':E'+r});}catch(e){issue(name+'!B'+r+':E'+r,e.message,[]);}}
 }
 const sim=sheet('Simulação do Método');settings.simulator={income:cash(sim,'D7'),bps:[9,10,11].map(r=>Math.round(Number(get(sim,'C'+r))*10000))};F.allocate(settings.simulator.income,settings.simulator.bps);warnings.push('Simulador: preservados os percentuais das células C9:C11, independentemente do título 50x30x20.');
 const res=sheet('Reserva Ideal');settings.reserve={employed:norm(get(res,'E7'))==='sim',children:norm(get(res,'E8'))==='sim',support:norm(get(res,'E9'))==='sim',cost:cash(res,'E10'),accumulated:0,goalId:''};checks.push({sheet:'Reserva Ideal',sourceTarget:v(res,'E15'),importTarget:F.reserve(settings.reserve).target/100});
 const goals=sheet('Metas Financeiras');if(norm(get(goals,'B19'))!=='meta'||norm(get(goals,'L19'))!=='janeiro')throw Error('Estrutura de acompanhamento das metas mudou.');const list=new Map();for(let r=6;r<=13;r++)if(get(goals,'B'+r))list.set(norm(get(goals,'B'+r)),{target:cash(goals,'I'+r),reason:get(goals,'D'+r),deadline:get(goals,'J'+r),row:r});
 const imported=new Set();for(let r=20;r<=29;r++){const title=get(goals,'B'+r);if(!title)continue;const ref=list.get(norm(title));let target=cash(goals,'C'+r);let deadline=excelDate(get(goals,'D'+r));let fallback=false;if(!target&&ref?.target){if(!opts.useGoalList){issue('Metas Financeiras!C'+r,'Valor ausente no acompanhamento. Autorize usar a lista superior na conferência.',ref);continue;}target=ref.target;fallback=true;}
 if(!deadline&&ref?.deadline&&opts.useGoalList){const m=norm(ref.deadline).match(/^([a-z]{3})\/(\d{4})$/);const mi=m?F.MONTHS.map(norm).indexOf(m[1]):-1;if(mi>=0){deadline=F.date(+m[2],mi+1,31);fallback=true;}}
 if(!target){issue('Metas Financeiras!C'+r,'Meta sem valor-alvo.',title);continue;}
 const g=put('goal',{name:title,target,initial:cash(goals,'E'+r),deadline:deadline||'',reason:String(ref?.reason||''),account:String(get(goals,'I'+r)),source:'Metas Financeiras!B'+r+':W'+r});imported.add(norm(title));if(fallback)warnings.push(`${title}: dados ausentes completados pela lista superior; prazo mensal convertido no último dia do mês com sua autorização.`);
 for(let m=1;m<=12;m++){const key=String.fromCharCode(75+m)+r;try{const amount=cash(goals,key);if(amount>0)put('contribution',{goalId:g.id,date:F.date(year,m,1),amount,source:'Metas Financeiras!'+key,periodOnly:true});}catch(e){issue('Metas Financeiras!'+key,e.message,null);}}
 const total=g.initial+records.filter(x=>x.kind==='contribution'&&x.goalId===g.id).reduce((a,x)=>a+x.amount,0);checks.push({sheet:'Meta: '+title,sourceTotal:v(goals,'J'+r),importTotal:total/100});}
 for(const [key,g]of list)if(!imported.has(key)&&!issues.some(x=>x.raw===g)){warnings.push('Meta da lista sem acompanhamento completo: '+key+'. Consulte os itens de revisão.');}
 warnings.push(`Os aportes mensais são atribuídos a ${year}; dia 01 representa apenas a competência, pois a origem não informa o dia. Aportes acompanham metas e não criam uma segunda saída no caixa.`);
 const cards=sheet('Controle de Cartões');for(const start of [7,47,87,127,167]){if(norm(get(cards,'B'+start))!=='data'||norm(get(cards,'E'+start))!=='valor total')throw Error('Estrutura de cartões mudou.');const number=(start===7?1:(start-7)/40+1);const c=put('card',{name:'Banco '+number,closing:0,due:0,limit:0,bestDay:String(get(cards,'D'+(start-1))),source:'Controle de Cartões!B'+start});for(let r=start+2;r<start+35;r++){if(!get(cards,'C'+r)&&!get(cards,'E'+r))continue;const raw=['B','C','D','E','F'].map(k=>get(cards,k+r));const loc='Controle de Cartões!B'+r+':S'+r;if(opts.cardSource!=='detailed'){issue(loc,'Compra preservada para revisão; fonte selecionada são os lançamentos mensais. Use a opção de parcelas para importar compras.',raw);continue;}try{const [d,n,categoryName,total,count]=raw,amount=F.money(total),category=cat(categoryName||'Compras no cartão');const date=excelDate(d);if(!date)throw Error('Data da compra não definida.');const schedule=[];for(let m=1;m<=12;m++){const val=cash(cards,String.fromCharCode(71+m)+r);if(val>0)schedule.push({date:F.date(year,m,1),amount:val});}if(schedule.reduce((a,x)=>a+x.amount,0)!==amount)throw Error('Meses das parcelas não somam o valor total. Revise a distribuição na origem.');put('purchase',{name:n,categoryId:category.id,cardId:c.id,amount,count:Number(count),date,firstDue:schedule[0].date,schedule,source:loc});}catch(e){issue(loc,e.message,raw);}}}
 warnings.push('Cartões: configure fechamento e vencimento antes de cadastrar novas compras. Pagamentos de fatura não contam novamente quando as parcelas detalhadas são usadas.');
 const debts=sheet('Dívidas');for(let r=7;r<=27;r++){if(!get(debts,'A'+r))continue;try{const date=excelDate(get(debts,'B'+r));if(!date)throw Error('Data inicial ausente.');put('debt',{name:String(get(debts,'A'+r)),date,installment:cash(debts,'C'+r),count:Number(get(debts,'D'+r)),paidBefore:Number(get(debts,'E'+r)),interest:String(get(debts,'H'+r)),cet:String(get(debts,'I'+r)),reason:String(get(debts,'J'+r)),source:'Dívidas!A'+r+':J'+r});}catch(e){issue('Dívidas!A'+r+':J'+r,e.message,[]);}}
 warnings.push('Dívidas: “parcela atual” é tratada como quantidade já paga, conforme G7=C7*(D7-E7). Revise essa quantidade. As referências incorretas de G8:G27 não são reproduzidas.');
 const assets=sheet('Patrimônio');for(let r=5;r<=13;r++){if(!get(assets,'B'+r))continue;for(let m=1;m<=12;m++){const cell=String.fromCharCode(66+m)+r;if(v(assets,cell)===undefined)continue;put('asset',{name:String(get(assets,'B'+r)),amount:cash(assets,cell),date:F.date(year,m,1),group:'Patrimônio',source:'Patrimônio!'+cell});}}
 const achievements=sheet('Escada da Conquista');for(let i=0;i<7;i++){const col=String.fromCharCode(65+i);put('achievement',{name:String(get(achievements,col+(20-i*2))).trim().replace(/\s+/g,' '),done:get(achievements,col+(14-i*2))===true,source:'Escada da Conquista!'+col+(20-i*2)});}
 const wishes=sheet('MENU INICIAL');for(let r=19;r<=34;r++){if(!get(wishes,'B'+r))continue;try{put('wish',{name:String(get(wishes,'B'+r)),amount:cash(wishes,'E'+r),need:String(get(wishes,'F'+r)),urgency:String(get(wishes,'H'+r)),priority:Number(get(wishes,'J'+r))||3,date:excelDate(get(wishes,'K'+r))||'',source:'MENU INICIAL!B'+r+':K'+r});}catch(e){issue('MENU INICIAL!B'+r+':K'+r,e.message,[]);}}
 const errors=Object.values(book.sheets).reduce((a,s)=>a+Object.values(s.cells).filter(c=>c.error).length,0);if(errors)warnings.push(`${errors} células da origem têm erros calculados, principalmente divisões por zero em campos vazios; elas não viram lançamentos.`);
 return {hash,name,year,records,settings,warnings,issues,checks,counts:records.reduce((a,r)=>(a[r.kind]=(a[r.kind]||0)+1,a),{}),options:opts};
}
module.exports={readXlsx,fromSnapshot,readFile,planImport,excelDate};
