import {esc} from './review-ui.js';
export async function openCatalog(request){
 const opener=document.activeElement,d=document.createElement('dialog');d.className='csv-dialog catalog-dialog';d.dataset.financialDialog='true';d.setAttribute('aria-label','Catálogo de categorias');
 d.innerHTML='<div class="dialog-heading"><h2>Catálogo de categorias</h2><button type="button" data-close>Fechar</button></div><div data-content>Carregando…</div><p data-error role="alert"></p>';
 document.body.append(d);let busy=false,data;
 d.querySelector('[data-close]').onclick=()=>{if(!busy)d.close();};d.addEventListener('cancel',e=>{if(busy)e.preventDefault();});d.addEventListener('close',()=>{d.remove();if(opener?.isConnected)opener.focus();},{once:true});d.showModal();
 const error=e=>{if(d.isConnected)d.querySelector('[data-error]').textContent=e.message;};
 async function load(){data=await request('catalog-list');if(!d.isConnected)return;render();}
 function render(){d.querySelector('[data-content]').innerHTML=`<p>Compartilhamos apenas palavras-chave genéricas. Seus extratos, valores e regras pessoais continuam privados.</p><button type="button" data-new class="primary">${data.isAdmin?'Criar regra global':'Sugerir regra'}</button><div data-editor></div><h3>Regras ${data.isAdmin?'do catálogo':'ativas'}</h3>${data.rules.map((r,i)=>`<div class="catalog-rule"><strong>${esc(r.merchant)}</strong><span>${esc(r.category||'Somente intermediador')} · v${r.version}${!r.active?' · Inativa':''}</span><small>${r.keywords.map(esc).join(' / ')}${r.exclusions.length?' · Exceto: '+r.exclusions.map(esc).join(' / '):''}</small>${data.isAdmin?`<button type="button" data-edit="${i}">Editar / desativar</button>`:''}</div>`).join('')}<h3>${data.isAdmin?'Sugestões aguardando aprovação':'Minhas sugestões'}</h3>${data.suggestions.map((r,i)=>`<div class="catalog-rule"><strong>${esc(r.merchant)}</strong><span>${esc(r.category||'Somente intermediador')} · ${esc(({pending:'Pendente',approved:'Aprovada',rejected:'Não aprovada'})[r.status])}</span><small>${r.keywords.map(esc).join(' / ')}</small>${data.isAdmin?`<button type="button" data-approve="${i}">Revisar e aprovar</button><button type="button" data-reject="${i}">Rejeitar</button>`:''}</div>`).join('')||'<p>Nenhuma sugestão pendente.</p>'}<p class="tiny">Mostrando até 100 sugestões recentes. Alterações valem para próximas importações; lançamentos já salvos são preservados.</p>`;}
 function edit(rule={},suggestionId=null){const form=document.createElement('form');form.className='panel';form.innerHTML=`<h3>${suggestionId?'Revisar sugestão':data.isAdmin?'Regra global':'Nova sugestão'}</h3><p class="tiny">Digite nomes genéricos. Não cole descrições do extrato, valores, documentos ou dados pessoais.</p><div class="form-grid"><label>Palavras-chave (separadas por vírgula)<input name="keywords" maxlength="1600" required value="${esc((rule.keywords||[]).join(', '))}"></label><label>Excluir quando contiver<input name="exclusions" maxlength="1600" value="${esc((rule.exclusions||[]).join(', '))}"></label><label>Estabelecimento<input name="merchant" maxlength="80" required value="${esc(rule.merchant||'')}"></label><label>Categoria sugerida (vazio: somente intermediador)<input name="category" maxlength="80" value="${esc(rule.category||'')}"></label>${data.isAdmin?`<label>Prioridade<input name="priority" type="number" min="0" max="1000" value="${rule.priority||0}" required></label><label><input name="active" type="checkbox" ${rule.active!==false?'checked':''}> Regra ativa</label>`:''}</div><label class="csv-include"><input name="confirm" type="checkbox" required> Confirmo que esta regra contém somente informações genéricas e pode ser compartilhada após aprovação.</label><div class="row"><button class="primary">${data.isAdmin?'Publicar regra':'Enviar sugestão'}</button><button type="button" data-cancel-editor>Cancelar</button></div>`;
 d.querySelector('[data-editor]').replaceChildren(form);form.querySelector('[name=keywords]').focus();form.querySelector('[data-cancel-editor]').onclick=()=>{form.remove();d.querySelector('[data-new]').focus();};
 form.onsubmit=async e=>{e.preventDefault();e.stopPropagation();const f=form.elements,split=v=>v.split(',').map(s=>s.trim()).filter(Boolean);await mutate(()=>request(data.isAdmin?'catalog-publish':'catalog-suggest',{rule_id:rule.rule_id||null,version:rule.version||0,suggestionId,keywords:split(f.keywords.value),exclusions:split(f.exclusions.value),merchant:f.merchant.value,category:f.category.value,priority:data.isAdmin?Number(f.priority.value):0,active:data.isAdmin?f.active.checked:true,confirmGeneric:f.confirm.checked}));};
 }
 async function mutate(fn){if(busy)return;busy=true;d.querySelector('[data-error]').textContent='';d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();await load();d.querySelector('[data-new]')?.focus();}catch(e){error(e);}finally{busy=false;d.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 d.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.hasAttribute('data-new'))edit();if(b.hasAttribute('data-edit'))edit(data.rules[+b.dataset.edit]);if(b.hasAttribute('data-approve')){const r=data.suggestions[+b.dataset.approve];edit(r,r.id);}if(b.hasAttribute('data-reject')){const r=data.suggestions[+b.dataset.reject];if(confirm('Rejeitar esta sugestão?'))mutate(()=>request('catalog-reject',{id:r.id}));}});
 try{await load();}catch(e){error(e);}
}
