import {installmentEstimates} from './intelligence.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const br=s=>s.split('-').reverse().join('/');
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
let range=null,page=0;
export const clearRange=()=>{range=null;page=0;};
export const getRange=()=>range;
export function rangeControl(){return `<button type="button" data-action="range-open" class="small ${range?'primary':''}" aria-haspopup="dialog" aria-label="Selecionar data inicial e de fechamento"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M4 5h16v16H4zM4 10h16M8 3v4M16 3v4"/></svg> ${range?br(range.start)+' – '+br(range.end):'Período'}</button>`;}
export function rangeAction(action,el,ctx){if(action==='range-page'){page=Math.max(0,page+Number(el.dataset.step));ctx.render();return;}if(action==='range-clear'){clearRange();ctx.render();return;}if(action!=='range-open')return;
 const F=window.F,trigger=document.activeElement,d=document.createElement('dialog');d.dataset.financialDialog='';d.setAttribute('aria-label','Período de cálculo');d.innerHTML=`<div class="dialog-heading"><h2>Período de cálculo</h2><button type="button" data-close aria-label="Fechar">×</button></div><form><div class="form-grid"><label>Dia inicial<input name="start" type="date" required value="${range?.start||ctx.period+'-01'}"></label><label>Dia de fechamento (inclusive)<input name="end" type="date" required value="${range?.end||F.date(+ctx.period.slice(0,4),+ctx.period.slice(5,7),31)}"></label></div><p>As duas datas entram no cálculo, mesmo quando o período atravessa meses ou anos.</p><p class="tiny">Débito usa a data da movimentação. Crédito usa o vencimento da parcela ou da fatura; a data original da compra continua preservada. Este filtro não altera o fechamento dos cartões.</p><p class="form-error" role="alert"></p><div class="dialog-footer"><button type="button" data-month>Voltar ao mês inteiro</button><button class="primary" type="submit">Aplicar período</button></div></form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.querySelector('[data-month]').onclick=()=>{clearRange();d.close();ctx.render();};d.addEventListener('close',()=>{d.remove();if(trigger?.isConnected)trigger.focus();},{once:true});d.querySelector('form').onsubmit=e=>{e.preventDefault();e.stopPropagation();const start=e.currentTarget.elements.start.value,end=e.currentTarget.elements.end.value;if(!F.validDate(start)||!F.validDate(end)||start>end){d.querySelector('[role=alert]').textContent='Informe datas válidas; o fechamento deve ser igual ou posterior ao início.';return;}range={start,end};page=0;d.close();ctx.render();};d.showModal();}
export function rangeRows(state,scope='all'){
 const F=window.F,cards=new Map(state.records.filter(r=>r.kind==='card').map(r=>[r.id,r]));let unknown=0;
 const rows=F.ledger(state.records).filter(r=>scope==='debit'?!r.cardId:scope==='credit'?!!r.cardId:scope==='all'||r.cardId===scope).map(r=>{let calculationDate=r.originalDate||r.date;if(r.cardId&&r.type!=='fatura'){if(r.derived)calculationDate=r.date;else if(r.invoicePeriod){const card=cards.get(r.cardId);calculationDate=card?.due?F.date(+r.invoicePeriod.slice(0,4),+r.invoicePeriod.slice(5,7),card.due):'';}}if(!calculationDate)unknown++;return {...r,calculationDate};}).filter(r=>r.calculationDate>=range.start&&r.calculationDate<=range.end).sort((a,b)=>b.calculationDate.localeCompare(a.calculationDate)||a.id.localeCompare(b.id));return {rows,unknown};
}
export function rangeReport(state,scope='all'){
 if(!range)return '';const F=window.F,{rows,unknown}=rangeRows(state,scope),sum=type=>rows.filter(r=>r.type===type).reduce((a,r)=>a+r.amount,0),s=F.summarize(rows,''),categories=new Map(state.records.filter(r=>r.kind==='category').map(r=>[r.id,r.name]));
 const estimates=installmentEstimates(state.installmentPlans,state.records).filter(r=>scope!=='debit'&&(scope==='all'||scope==='credit'||r.cardId===scope)&&r.dueDate>=range.start&&r.dueDate<=range.end),estimated=estimates.reduce((a,r)=>a+r.amount,0);
 const months=new Map(),groups=new Map();for(const r of rows){const month=r.calculationDate.slice(0,7);if(!months.has(month))months.set(month,[]);months.get(month).push(r);if(r.type==='despesa'){const name=categories.get(r.categoryId)||'Outros';groups.set(name,(groups.get(name)||0)+r.amount);}}
 const pages=Math.max(1,Math.ceil(rows.length/30));page=Math.min(page,pages-1);const cards=[['Receitas',s.income],['Despesas líquidas',s.expense],['Investimentos e dívidas',s.investment+s.debt],['Resultado do período',s.balance]];
 return `<div class="heading"><div><div class="eyebrow">PERÍODO PERSONALIZADO</div><h1>${scope==='debit'?'Contas e lançamentos':scope==='credit'?'Cartões':'Análise do período'}</h1><p>${br(range.start)} até ${br(range.end)} · ambas as datas incluídas</p></div><button data-action="range-clear">Voltar ao mês inteiro</button></div><div class="cards">${cards.map(([name,value])=>`<div class="stat"><p>${name}</p><strong class="stat-value">${money(value)}</strong></div>`).join('')}</div><p class="tiny">Transferências: ${money(sum('transferencia'))} · Pagamentos de faturas: ${money(sum('fatura'))} — não somados às despesas. Estornos já reduzem as despesas. Parcelas estimadas: ${money(estimated)}, separadas do resultado.</p>${unknown?`<p class="notice">${unknown} lançamento(s) de crédito sem vencimento definido ficaram fora do cálculo por dia. Configure o vencimento do cartão.</p>`:''}<section class="panel"><h2>Por mês dentro do intervalo</h2><div class="table-wrap"><table><thead><tr><th>Mês</th><th>Receitas</th><th>Despesas</th><th>Resultado</th></tr></thead><tbody>${[...months].sort(([a],[b])=>a.localeCompare(b)).map(([m,rs])=>{const x=F.summarize(rs,'');return `<tr><td>${m.split('-').reverse().join('/')}</td><td>${money(x.income)}</td><td>${money(x.expense)}</td><td>${money(x.balance)}</td></tr>`;}).join('')||'<tr><td colspan="4">Sem movimentos neste intervalo.</td></tr>'}</tbody></table></div></section><section class="panel"><h2>Despesas por categoria</h2>${[...groups].sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="bar-row"><div class="bar-label"><span>${esc(name)}</span><strong>${money(value)}</strong></div><progress max="${Math.max(1,...groups.values())}" value="${Math.max(0,value)}" style="width:100%" aria-label="${esc(name)}"></progress></div>`).join('')||'<p>Sem despesas.</p>'}</section><section class="panel"><h2>Lançamentos · ${rows.length}</h2><div class="table-wrap"><table><thead><tr><th>Data do cálculo</th><th>Data original</th><th>Descrição</th><th>Natureza</th><th>Categoria</th><th>Valor</th></tr></thead><tbody>${rows.slice(page*30,(page+1)*30).map(r=>`<tr><td>${br(r.calculationDate)}</td><td>${br(r.originalDate||r.date)}</td><td>${esc(r.description)}</td><td>${r.reversal?'Estorno':F.TYPES[r.type]}</td><td>${esc(categories.get(r.categoryId)||'—')}</td><td>${money(r.amount)}</td></tr>`).join('')}</tbody></table></div><div class="pagination"><button data-action="range-page" data-step="-1" ${page===0?'disabled':''}>Anterior</button><span>${page+1} / ${pages}</span><button data-action="range-page" data-step="1" ${page+1>=pages?'disabled':''}>Próxima</button></div></section><p class="notice">Filtro de análise: os vencimentos, as faturas e os pagamentos salvos não são alterados. Metas, patrimônio, reserva e orçamento planejado continuam com suas regras próprias; não são rateados por dias.</p>`;
}
