import {parseCSV,inspectCSV,validDate,suggestion,duplicates,reviewIndex,cents,recurringCandidates,forecast} from './csv-core.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((n||0)/100);
const date=s=>s?.split('-').reverse().join('/')||'';
const btn=(label,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
let selectedCard='',generation=0;
export function clearFinancial(){selectedCard='';generation++;document.querySelectorAll('[data-financial-dialog]').forEach(d=>{d.close();d.remove();});}
export const financeTabs=active=>`<nav class="finance-tabs" aria-label="Movimentações financeiras">${btn('Contas e lançamentos','navigate','data-route="entries"',active==='entries'?'primary':'')}${btn('Cartões de crédito','navigate','data-route="cards"',active==='cards'?'primary':'')}</nav>`;
export function cardsView(state,period,helpers){
 const cards=state.records.filter(r=>r.kind==='card'),card=cards.find(r=>r.id===selectedCard),ledger=window.F.ledger(state.records),readOnly=state.role==='consultant';
 const amount=id=>ledger.filter(r=>r.cardId===id&&r.type==='despesa'&&r.date.startsWith(period)).reduce((sum,r)=>sum+r.amount,0);
 if(!card)return financeTabs('cards')+`<div class="heading"><div><div class="eyebrow">FINANÇAS COM DIREÇÃO</div><h1>Cartões</h1><p>Abra um cartão para acompanhar sua fatura e importar compras de crédito.</p></div>${btn('Novo cartão','new-card','','primary')}</div><div class="goal-grid">${cards.map(c=>`<article class="goal-card clickable-card" data-action="finance-card" data-card="${esc(c.id)}" tabindex="0" role="link" aria-label="Abrir cartão ${esc(c.name)}"><div class="panel-head"><h2>${esc(c.name)}</h2><span aria-hidden="true">↗</span></div><p class="tiny">COMPROMISSO DO MÊS</p><div class="goal-money">${money(amount(c.id))}</div><div class="goal-meta"><span>Fechamento: ${c.closing||'configurar'}</span><span>Vencimento: ${c.due||'configurar'}</span></div><p>Limite informado: ${money(c.limit)}</p><div class="row">${btn('Abrir fatura','finance-card',`data-card="${esc(c.id)}"`,'primary')}${btn('Editar','edit',`data-id="${esc(c.id)}"`)}${btn('Excluir','delete',`data-id="${esc(c.id)}"`,'danger')}</div></article>`).join('')||'<section class="panel"><h2>Nenhum cartão cadastrado</h2><p>Adicione um cartão para organizar as compras de crédito.</p></section>'}</div>`;
 const rows=ledger.filter(r=>r.cardId===card.id&&r.date.startsWith(period)).sort((a,b)=>(b.originalDate||b.date).localeCompare(a.originalDate||a.date));
 const purchases=state.records.filter(r=>r.kind==='purchase'&&r.cardId===card.id);
 return financeTabs('cards')+`<div class="heading"><div><div class="eyebrow">FATURA · ${esc(period)}</div><h1>${esc(card.name)}</h1><p>Fechamento: dia ${card.closing||'não definido'} · Vencimento: dia ${card.due||'não definido'}</p></div>${btn('Todos os cartões','finance-back')}</div><section class="panel"><div class="panel-head"><div><span class="tiny">COMPRAS MENOS ESTORNOS · MÊS DA FATURA</span><div class="goal-money">${money(amount(card.id))}</div></div><div class="row">${btn('Nova compra','new-purchase',`data-card="${esc(card.id)}"`,'primary')}${btn('Importar fatura CSV','finance-import',`data-card="${esc(card.id)}"`)}</div></div><p class="tiny">Escolha o mês da fatura no topo. O valor considera os registros disponíveis; pode diferir do saldo cobrado pelo banco.</p></section><section class="panel"><h2>Movimentações da fatura</h2>${rows.length?helpers.entryTable(rows):'<p>Nenhuma movimentação neste mês. Importe o CSV da fatura ou registre uma compra.</p>'}</section>${recurringView(state,period,card.id)}<details class="panel"><summary>Compras cadastradas e parcelas futuras (${purchases.length})</summary>${purchases.map(p=>`<div class="bank-item"><strong>${esc(p.name)}</strong><p>${money(p.amount)} · ${p.count} parcela(s)</p><div class="row">${btn('Ver parcelas','schedule',`data-id="${esc(p.id)}"`)}${btn('Editar compra','edit',`data-id="${esc(p.id)}"`)}</div></div>`).join('')||'<p>Nenhuma compra parcelada cadastrada.</p>'}</details><div class="notice">O CSV importa somente as cobranças presentes na fatura, sem criar parcelas futuras. Pagamentos de fatura não acrescentam outra despesa. Extratos de débito são importados em Contas e lançamentos.</div>`;
}
export function recurringView(state,period,cardId=''){
 const rules=(state.recurringRules||[]).filter(r=>(r.cardId||'')===cardId),candidates=recurringCandidates(state.records).filter(r=>(r.cardId||'')===cardId&&!rules.some(x=>x.key===r.key)),expected=forecast(rules,state.records,period);
 const controls=r=>btn('Editar','finance-recurring',`data-key="${esc(r.key)}"`,'small')+btn(r.status==='ignored'?'Reativar':'Ignorar','finance-recurring',`data-key="${esc(r.key)}" data-mode="${r.status==='ignored'?'active':'ignored'}"`,'small flat')+btn('Remover previsão','finance-recurring-remove',`data-key="${esc(r.key)}"`,'small flat danger');
 return `<section class="panel"><h2>Assinaturas e recorrências</h2><p>Possíveis repetições mensais precisam da sua confirmação. Parcelas não são tratadas como assinaturas.</p>${candidates.map(r=>`<div class="bank-item"><div class="panel-head"><div><strong>${esc(r.name)}</strong><p>${money(r.amount)} · ${r.occurrences} meses consecutivos semelhantes${r.account?' · '+esc(r.account):''}</p></div>${btn('É uma assinatura?','finance-recurring',`data-key="${esc(r.key)}"`,'primary small')}${btn('Ignorar','finance-recurring',`data-key="${esc(r.key)}" data-mode="ignored"`,'small')}</div></div>`).join('')}${rules.filter(r=>r.status==='active').map(r=>{const f=expected.find(x=>x.key===r.key);return `<div class="bank-item"><strong>${esc(r.name)}</strong><p>${money(r.amount)} · ${f?(f.actual?'Cobrança registrada neste mês':'Previsão para '+date(f.date)):'Próxima previsão: '+date(r.nextDate)}</p>${controls(r)}</div>`;}).join('')}${!candidates.length&&!rules.some(r=>r.status==='active')?'<p class="tiny">Ainda não há recorrências confirmadas. Importe o histórico de pelo menos dois meses para procurar padrões.</p>':''}${rules.some(r=>r.status==='ignored')?`<details><summary>Recorrências ignoradas</summary>${rules.filter(r=>r.status==='ignored').map(r=>`<div class="bank-item">${esc(r.name)} ${controls(r)}</div>`).join('')}</details>`:''}<p class="tiny">Previsões não entram como despesas. Uma cobrança com a mesma descrição, conta ou cartão e mês retira a previsão pendente desse mês.</p></section>`;
}
export function forecastView(state,period){const rows=forecast(state.recurringRules,state.records,period).filter(r=>!r.actual);return rows.length?`<section class="panel"><h2>Recorrências previstas</h2><div class="goal-money">${money(rows.reduce((s,r)=>s+r.amount,0))}</div><p>${rows.length} cobrança(s) prevista(s) ainda sem lançamento correspondente em ${esc(period)}. Não incluídas nas despesas realizadas.</p>${rows.map(r=>`<p>${esc(r.name)} · ${money(r.amount)} · ${date(r.date)} · ${esc(r.cardId?state.records.find(c=>c.id===r.cardId)?.name:r.account||'Conta')}</p>`).join('')}</section>`:'';}
function dialog(title){const d=document.createElement('dialog');d.dataset.financialDialog='true';d.className='csv-dialog';d.innerHTML=`<div class="dialog-heading"><h2>${esc(title)}</h2><button type="button" data-close>Fechar</button></div><div data-body></div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
async function importDialog(state,period,cardId,deps){
 if(state.role!=='owner')throw Error('Somente o titular pode importar.');
 const classification=reviewIndex(state.records,window.F.ledger(state.records));
 const epoch=generation,d=dialog(cardId?'Importar fatura de crédito':'Importar extrato de conta'),body=d.querySelector('[data-body]');let parsed=null,text='',filename='',context=null,choices=[],page=0,saving=false,reading=0;
 const accounts=[...new Set(state.records.filter(r=>r.kind==='entry'&&r.account).map(r=>r.account))];
 body.innerHTML=`<p>CSV Nubank ou outro banco com mapeamento de colunas · até 2 MB e 2.000 movimentações. Nada será salvo antes da confirmação.</p><form id="csv-setup"><div class="form-grid">${cardId?`<div class="field"><label>Mês da fatura<input name="period" type="month" value="${esc(period)}" required></label></div>`:`<div class="field"><label>Nome da conta<input name="account" list="csv-accounts" maxlength="80" placeholder="Ex.: Nubank pessoal" required></label><datalist id="csv-accounts">${accounts.map(a=>`<option value="${esc(a)}"></option>`).join('')}</datalist></div>`}<div class="field"><label>Arquivo CSV<input name="file" type="file" accept=".csv,text/csv" required></label></div></div><div data-mapping></div><button type="submit" class="primary">Conferir arquivo</button></form><p data-error role="alert"></p><div data-review></div>`;
 const error=message=>{if(d.isConnected)d.querySelector('[data-error]').textContent=message;};
 const options=type=>{const actual=type==='estorno'?'despesa':type;return state.records.filter(c=>c.kind==='category'&&!c.archived&&c.type===actual);};
 const fields=row=>{const c=choices[row.index],types=cardId?['despesa','estorno','fatura']:['despesa','receita','transferencia','fatura','estorno','investimento','divida','saldo'];return `<article class="csv-row" data-index="${row.index}"><div class="panel-head"><label class="csv-include"><input type="checkbox" data-field="include" ${c.include?'checked':''} ${row.exact?'disabled':''}> Adicionar linha ${row.index+2}</label><span class="tag">${row.exact?'Já importada':row.issues.length?'Revisar linha':row.possible?'Possível duplicidade':row.installment?'Parcela — sem gerar próximas':row.signed<0?'Valor negativo no CSV':'Valor positivo no CSV'}</span></div>${row.issues.length?`<div class="notice"><strong>Registro ${row.index+2}: precisa de revisão</strong><p>${row.issues.map(esc).join(" ")}</p><p>Data original: ${esc(row.rawDate)} · Valor original: ${esc(row.rawAmount)}</p><p>Corrija os campos abaixo ou deixe esta linha desmarcada.</p><details><summary>Colunas originais</summary><p>${row.raw.map(esc).join(" · ")}</p></details><label class="csv-include"><input type="checkbox" data-field="acceptCorrection" ${c.acceptCorrection?"checked":""}> Corrigi esta linha e conferi sua natureza e valor.</label></div>`:""}<div class="form-grid"><label>Data original<input type="date" data-field="date" value="${esc(c.date)}" ${row.exact?'disabled':''}></label><label>Descrição<input data-field="description" maxlength="2000" value="${esc(c.description)}" ${row.exact?'disabled':''}></label><label>Valor absoluto (R$)<input data-field="amountText" inputmode="decimal" value="${esc(c.amountText)}" ${row.exact?'disabled':''}></label><label>Natureza<select data-field="type" ${row.exact?'disabled':''}><option value="">Revisar natureza…</option>${types.map(t=>`<option value="${t}" ${c.type===t?'selected':''}>${t==='estorno'?'Estorno de despesa':window.F.TYPES[t]}</option>`).join('')}</select></label><label>Categoria<select data-field="categoryId" ${row.exact||!c.type||c.type==='transferencia'?'disabled':''}><option value="">Nova categoria / sugestão…</option>${options(c.type).map(cat=>`<option value="${esc(cat.id)}" ${c.categoryId===cat.id?'selected':''}>${esc(cat.name)}</option>`).join('')}</select></label><label>Nome da nova categoria<input data-field="categoryName" maxlength="80" value="${esc(c.categoryName)}" ${row.exact||c.categoryId||!c.type||c.type==='transferencia'?'disabled':''}></label></div>${row.possible?`<label class="csv-include"><input type="checkbox" data-field="acceptDuplicate" ${c.acceptDuplicate?'checked':''}> Conferi: esta é outra movimentação, não uma repetição do lançamento existente.</label>`:''}${!c.type?'<p class="tiny">Pix, transferências e créditos sem identificação precisam de classificação. Uma transferência entre suas contas não é receita nem despesa.</p>':''}</article>`;};
 function summary(){let total=0,income=0,out=0,refund=0,other=0;for(const c of choices.filter(c=>c.include)){total++;let value;try{value=cents(c.amountText);}catch{continue;}if(c.type==='receita')income+=value;else if(c.type==='estorno')refund+=value;else if(['despesa','divida','investimento'].includes(c.type))out+=value;else other+=value;}return `${parsed.length} identificada(s) · ${parsed.filter(r=>r.issues.length).length} com problemas na origem · ${parsed.length-total} não selecionada(s) · ${total} selecionada(s) · Receitas: ${money(income)} · Saídas/alocações: ${money(out)} · Estornos: ${money(refund)} · Demais naturezas: ${money(other)}`;}
 function renderReview(){if(!parsed||!d.isConnected)return;const target=d.querySelector('[data-review]');target.innerHTML=`<h3>Confira antes de adicionar</h3><p>${esc(filename)} · ${cardId?'Fatura '+esc(context.period):esc(context.account)}</p><p>As categorias são sugestões editáveis. Nomes novos serão criados somente ao confirmar. Pagamentos de fatura e transferências entre suas contas ficam fora das despesas.</p><p data-summary role="status">${summary()}</p><div class="row"><button type="button" data-select>Selecionar disponíveis desta página</button><button type="button" data-unselect>Desmarcar esta página</button></div>${parsed.slice(page*25,(page+1)*25).map(fields).join('')}<div class="pagination"><button type="button" data-prev ${page===0?'disabled':''}>Anterior</button><span>Página ${page+1} / ${Math.ceil(parsed.length/25)}</span><button type="button" data-next ${(page+1)*25>=parsed.length?'disabled':''}>Próxima</button></div><label class="csv-include"><input type="checkbox" data-confirm> Conferi as linhas selecionadas, o destino e as possíveis duplicidades. Desejo adicionar estas movimentações à minha conta.</label><label class="csv-include"><input type="checkbox" data-skip> Autorizo continuar sem as linhas com problemas que deixei desmarcadas.</label><p data-commit-error role="alert"></p><button type="button" class="primary" data-commit>Adicionar movimentações</button>`;
 target.querySelectorAll('[data-field]').forEach(input=>input.addEventListener('change',()=>{const index=Number(input.closest('[data-index]').dataset.index),field=input.dataset.field,c=choices[index];c[field]=input.type==='checkbox'?input.checked:input.value;if(field==='type'){const hint=suggestion({...parsed[index],type:c.type},state.records,classification);c.categoryId=hint.categoryId;c.categoryName=hint.categoryName;}if(['date','description','amountText','type'].includes(field)){c.acceptCorrection=false;c.acceptDuplicate=false;let amount=0;try{amount=Math.abs(cents(c.amountText));}catch{}const match=duplicates({...parsed[index],date:c.date,description:c.description,amount},state.records,[],classification);parsed[index].possible=match.possible;}if(['type','categoryId','date','description','amountText'].includes(field))renderReview();else{target.querySelector('[data-summary]').textContent=summary();target.querySelector('[data-confirm]').checked=false;}}));
 target.querySelector('[data-prev]').onclick=()=>{page--;renderReview();};target.querySelector('[data-next]').onclick=()=>{page++;renderReview();};
 for(const [selector,on]of [['[data-select]',true],['[data-unselect]',false]])target.querySelector(selector).onclick=()=>{for(const r of parsed.slice(page*25,(page+1)*25))if(!r.exact&&(!on||(!r.possible&&!r.issues.length)))choices[r.index].include=on;renderReview();};
 target.querySelector('[data-commit]').onclick=async()=>{
  if(saving)return;const err=target.querySelector('[data-commit-error]');err.textContent='';
  try{
   if(epoch!==generation||!d.isConnected)throw Error('A conta mudou. Abra a importação novamente.');
   if(!target.querySelector('[data-confirm]').checked)throw Error('Marque a confirmação após revisar as movimentações.');
   const selected=choices.filter(c=>c.include).map(c=>{try{return {...c,amount:cents(c.amountText)};}catch(e){throw Error('Linha '+(c.index+2)+': '+e.message);}});if(!selected.length)throw Error('Selecione ao menos uma movimentação.');
   if(parsed.some(r=>r.issues.length&&!choices[r.index].include)&&!target.querySelector('[data-skip]').checked)throw Error('Autorize continuar sem as linhas com problemas desmarcadas.');
   for(const c of selected){if(parsed[c.index].issues.length&&!c.acceptCorrection)throw Error('Confirme a correção da linha '+(c.index+2)+'.');if(!c.type||c.amount<=0||!validDate(c.date)||!c.description.trim())throw Error('Revise os campos da linha '+(c.index+2)+'.');if(c.type!=='transferencia'&&!c.categoryId&&!c.categoryName.trim())throw Error('Escolha a categoria da linha '+(c.index+2)+'.');if(parsed[c.index].possible&&!c.acceptDuplicate)throw Error('Confira a possível duplicidade da linha '+(c.index+2)+'.');}
   saving=true;d.querySelectorAll('button,input,select').forEach(x=>x.disabled=true);
   const result=await deps.call('csv-import',{text,name:filename,context,decisions:selected,confirm:true,acceptSkipped:target.querySelector('[data-skip]').checked});
   if(epoch!==generation)return;d.close();await deps.refresh();deps.message(`${result.count} movimentação(ões) adicionada(s).`);
  }catch(e){if(d.isConnected){err.textContent=e.message;d.querySelectorAll('button,input,select').forEach(x=>x.disabled=false);renderReview();d.querySelector('[data-commit-error]').textContent=e.message;}}finally{saving=false;}
 };
 }
 d.addEventListener('cancel',e=>{if(saving)e.preventDefault();});
 d.querySelector('#csv-setup').addEventListener('change',event=>{if(saving)return;if(event.target.name==='file')d.querySelector('[data-mapping]').innerHTML='';reading++;parsed=null;choices=[];d.querySelector('[data-review]').innerHTML='';});
 d.querySelector('#csv-setup').addEventListener('submit',async e=>{e.preventDefault();e.stopPropagation();if(saving)return;const token=++reading;error('');parsed=null;d.querySelector('[data-review]').innerHTML='';try{const form=e.currentTarget,file=form.elements.file.files[0];if(!file||!file.name.toLowerCase().endsWith('.csv')||file.size>2*1024*1024)throw Error('Selecione um arquivo .csv de até 2 MB.');const chosen={cardId,period:cardId?form.elements.period.value:'',account:cardId?'':form.elements.account.value.trim()};const bytes=await file.arrayBuffer();let contents;try{contents=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{contents=new TextDecoder('windows-1252').decode(bytes);}if(epoch!==generation||token!==reading||!d.isConnected)return;const info=inspectCSV(contents);if(info.format==='mapped'){
 const mapping=d.querySelector('[data-mapping]');if(!mapping.querySelector('[name=mapDate]')){const columnOptions='<option value="-1">Selecione…</option>'+info.headers.map((h,i)=>`<option value="${i}">${i+1}. ${esc(h)}</option>`).join('');mapping.innerHTML=`<div class="notice"><h3>Identifique as colunas deste banco</h3><p>Formato não reconhecido automaticamente. Selecione uma coluna de valor com sinal. Arquivos com débito e crédito em colunas separadas precisam ser reorganizados antes da importação.</p><p>As naturezas serão escolhidas na conferência, pois a convenção de sinais varia entre bancos.</p></div><div class="form-grid"><label>Banco<input name="bank" maxlength="80" required></label><label>Data<select name="mapDate">${columnOptions}</select></label><label>Descrição<select name="mapDescription">${columnOptions}</select></label><label>Valor<select name="mapAmount">${columnOptions}</select></label><label>Identificador (opcional)<select name="mapId"><option value="-1">Sem identificador</option>${info.headers.map((h,i)=>`<option value="${i}">${i+1}. ${esc(h)}</option>`).join('')}</select></label><label>Formato das datas<select name="dateFormat"><option value="">Escolha…</option><option value="dmy">Dia / mês / ano</option><option value="mdy">Mês / dia / ano</option><option value="iso">Ano-mês-dia (ISO)</option></select></label><label>Separador decimal<select name="decimal"><option value="auto">Automático — sinalizar ambiguidades</option><option value="comma">Vírgula: 1.234,56</option><option value="dot">Ponto: 1,234.56</option></select></label></div><details><summary>Primeiros registros do arquivo</summary>${info.rows.slice(0,3).map(row=>`<p>${row.map(esc).join(' · ')}</p>`).join('')}</details>`;error('Preencha o mapeamento e clique novamente em Conferir arquivo.');return;}
 chosen.bank=form.elements.bank.value.trim();chosen.mapping={date:Number(form.elements.mapDate.value),description:Number(form.elements.mapDescription.value),amount:Number(form.elements.mapAmount.value),id:Number(form.elements.mapId.value),dateFormat:form.elements.dateFormat.value,decimal:form.elements.decimal.value};
 }const rows=await parseCSV(contents,chosen);if(epoch!==generation||token!==reading||!d.isConnected)return;const ledger=window.F.ledger(state.records);parsed=rows.map(r=>({...r,...duplicates(r,state.records,ledger,classification)}));choices=parsed.map(r=>({index:r.index,include:!r.exact&&!r.possible&&!r.issues.length,type:r.type,description:r.description,date:r.date,amountText:r.signed===null?'':(r.amount/100).toFixed(2).replace('.',','),...suggestion(r,state.records,classification),acceptDuplicate:false,acceptCorrection:false}));text=contents;filename=file.name;context=chosen;page=0;renderReview();}catch(e){error(e.message);}});
}
function recurringDialog(state,key,mode,deps){
 if(state.role!=='owner')throw Error('Somente o titular pode confirmar recorrências.');
 const rule=(state.recurringRules||[]).find(r=>r.key===key),candidate=recurringCandidates(state.records).find(r=>r.key===key),r=rule||candidate;if(!r)throw Error('Recorrência indisponível.');
 const d=dialog('Assinatura ou despesa mensal'),epoch=generation;let saving=false;
 d.querySelector('[data-body]').innerHTML=`<p>Confirme ou ajuste a previsão. Nenhum lançamento futuro será criado.</p><form><div class="form-grid"><label>Nome<input name="name" maxlength="2000" value="${esc(r.name)}" required></label><label>Valor previsto (R$)<input name="amount" inputmode="decimal" value="${(r.amount/100).toFixed(2).replace('.',',')}" required></label><label>Próxima cobrança prevista<input name="nextDate" type="date" value="${esc(rule?.nextDate||window.F.addMonths(candidate.lastDate,1))}" required></label><label>Status<select name="status"><option value="active" ${(mode||rule?.status)==='ignored'?'':'selected'}>Ativa</option><option value="ignored" ${(mode||rule?.status)==='ignored'?'selected':''}>Ignorada / cancelada</option></select></label></div><p class="tiny">O vínculo com as cobranças usa a descrição original. Alterar o nome aqui muda somente o nome da previsão.</p><p data-error role="alert"></p><button type="submit" class="primary">Salvar recorrência</button></form>`;
 d.addEventListener('cancel',e=>{if(saving)e.preventDefault();});
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();e.stopPropagation();if(saving)return;try{if(epoch!==generation)throw Error('A conta mudou.');const f=e.currentTarget.elements,amount=cents(f.amount.value);if(amount<=0)throw Error('Informe um valor positivo.');saving=true;d.querySelectorAll('button').forEach(b=>b.disabled=true);await deps.call('recurring-save',{key,name:f.name.value,amount,nextDate:f.nextDate.value,status:f.status.value});if(epoch!==generation)return;d.close();await deps.refresh();deps.message('Recorrência salva.');}catch(err){if(d.isConnected){d.querySelector('[data-error]').textContent=err.message;d.querySelectorAll('button').forEach(b=>b.disabled=false);}}finally{saving=false;}};
}
export async function financialAction(action,el,ctx,deps){
 if(action==='finance-card'){selectedCard=el.dataset.card;ctx.render();return;}
 if(action==='finance-back'){selectedCard='';ctx.render();return;}
 if(action==='finance-import')return importDialog(ctx.state,ctx.period,el.dataset.card||'',deps);
 if(action==='finance-recurring-remove'){if(ctx.state.role!=='owner')throw Error('Somente o titular pode alterar recorrências.');if(confirm('Remover esta previsão? Os lançamentos existentes serão preservados. A sugestão poderá reaparecer pelo histórico.')){await deps.call('recurring-remove',{key:el.dataset.key});await deps.refresh();}return;}
 if(action==='finance-recurring')return recurringDialog(ctx.state,el.dataset.key,el.dataset.mode,deps);
 throw Error('Ação financeira indisponível.');
}
