import {savedRows,revealSavedRow} from './saved-review.js';
import {monthLabel} from './review-ui.js';
import {categoryKey,merchantName,installmentInfo,installmentEstimates,expectedPart,needsReview} from './intelligence.mjs';
import {cents} from './csv-core.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((n||0)/100);
const date=s=>String(s||'').split('-').reverse().join('/');
const btn=(label,action,extra='',cls='small')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const warning='<span class="estimate-warning" role="img" aria-label="Atenção: parcela estimada">⚠</span> Parcela estimada — ainda não confirmada por uma fatura importada.';
let activeMonth='',monthScope='',calendarYear='';
export function clearIntelligence(){activeMonth='';monthScope='';calendarYear='';}
export function entryMeta(entry){const info=installmentInfo(entry.description);return `<span class="tiny muted">${esc(merchantName(entry.description))}${info?' · Parcela '+info.number+'/'+info.total:''}${entry.reversal?' · Estorno':''}</span>`;}
export function entryActions(entry){return entry.derived||entry.locked||entry.type==='transferencia'?'':btn('Categoria e regra','finance-category',`data-id="${esc(entry.id)}"`,'small flat');}
export function rulesView(state){const rules=state.categoryRules||[];return `<section class="panel"><h2>Regras das próximas importações</h2>${state.role==='owner'?btn('Regras de natureza: estornos e pagamentos','finance-nature-rules'):''}<p>Regras privadas da sua conta, aplicadas por estabelecimento e natureza. Removê-las não altera lançamentos salvos.</p>${rules.map(r=>`<div class="bank-item"><strong>${esc(r.key)}</strong><p>${esc(window.F.TYPES[r.type])} · ${esc(state.records.find(c=>c.id===r.categoryId)?.name||'Categoria indisponível')}</p>${btn('Remover regra','finance-rule-remove',`data-key="${esc(r.key)}" data-type="${esc(r.type)}"`,'small danger')}</div>`).join('')||'<p>Nenhuma regra personalizada. Use “Categoria e regra” em um lançamento ou salve uma regra na conferência do CSV.</p>'}</section>`;}
export function installmentSummary(state,period){const estimates=installmentEstimates(state.installmentPlans,state.records).filter(x=>x.period===period),pending=state.installmentPending||[];if(!estimates.length&&!pending.length)return '';const confirmed=window.F.summarize(window.F.ledger(state.records),period).expense,total=estimates.reduce((s,r)=>s+r.amount,0);return `<section class="panel"><h2>Despesas e parcelas previstas · ${esc(period)}</h2><div class="cards"><div><p>Confirmado / cadastrado</p><strong>${money(confirmed)}</strong></div><div><p>Parcelas estimadas</p><strong>${money(total)}</strong></div><div><p>Compromisso previsto</p><strong>${pending.length?'Aguardando conferência':money(confirmed+total)}</strong></div></div><p class="tiny">As estimativas ficam fora das despesas realizadas e dos gráficos de gastos. Previsões de assinaturas são mostradas separadamente.</p>${pending.length?`<p class="notice">${pending.length} cobrança(s) aguardam conferência de parcelas na página dos cartões. O compromisso previsto pode conter sobreposição enquanto esses vínculos não forem resolvidos.</p>`:''}</section>`;}
export function monthlyCardView(state,period,card,helpers){
 const scope=card.id+'|'+period;if(monthScope!==scope){monthScope=scope;activeMonth=undefined;calendarYear='';}
 const ledger=window.F.ledger(state.records).filter(r=>r.cardId===card.id),plans=(state.installmentPlans||[]).filter(p=>p.cardId===card.id),estimates=installmentEstimates(plans,state.records),pending=(state.installmentPending||[]).filter(p=>state.records.some(r=>r.id===p.entryId&&r.cardId===card.id));
 const months=[...new Set([period,...ledger.map(r=>r.date.slice(0,7)),...estimates.map(r=>r.period)])].sort().reverse();
 const monthRows=month=>ledger.filter(r=>r.date.startsWith(month)),sum=rows=>rows.filter(r=>r.type==='despesa').reduce((s,r)=>s+r.amount,0);
 if(activeMonth===undefined)activeMonth=months.slice().sort().find(m=>monthRows(m).some(r=>needsReview(r)))??months[0];
 if(!calendarYear)calendarYear=(activeMonth||period).slice(0,4);
 const focusMonth=activeMonth||period,confirmed=sum(monthRows(focusMonth)),estimated=estimates.filter(r=>r.period===focusMonth).reduce((s,r)=>s+r.amount,0);
 const summary=`<section class="panel invoice-summary"><h2>${esc(monthLabel(focusMonth))}</h2><div class="cards"><div><p>Confirmado / cadastrado</p><strong>${money(confirmed)}</strong></div><div><p>Estimado</p><strong>${money(estimated)}</strong></div><div><p>Compromisso previsto</p><strong>${pending.length?btn('Resolver '+pending.length+' vínculo'+(pending.length>1?'s':''),'finance-notifications',`data-card="${esc(card.id)}"`,'small'):money(confirmed+estimated)}</strong></div></div><p class="tiny">Compras menos estornos. Pagamentos de fatura não geram outra despesa. Estimativas não são gastos confirmados.</p></section>`;
 const rows=monthRows(focusMonth),projected=estimates.filter(x=>x.period===focusMonth);
 return `<section class="invoice-months"><h2>Calendário de faturas</h2>${invoiceCalendar(months,monthRows,estimates,sum)}${summary}<section class="panel invoice-selected" aria-label="Fatura selecionada"><h3>Cobranças registradas · ${esc(monthLabel(focusMonth))}</h3>${rows.length?savedRows(state,rows,'card:'+card.id+':'+focusMonth):'<p>Nenhuma cobrança registrada neste mês.</p>'}${projected.length?`<details><summary>Parcelas futuras estimadas · ${projected.length}</summary>${projected.map(r=>`<div class="bank-item"><strong>${esc(r.name)} · ${r.number}/${r.total}</strong><p>${esc(r.merchant)} · ${money(r.amount)}${r.dueDate?" · vencimento estimado "+date(r.dueDate):" · configure o vencimento do cartão"}</p><p class="estimate-notice">${warning}</p>${btn('Editar previsão','finance-installment-edit',`data-plan="${esc(r.planId)}" data-number="${r.number}"`)}</div>`).join('')}</details>`:''}</section></section>`;

}
export function cardPending(state,cardId){
 const ambiguous=new Set((state.installmentPending||[]).map(p=>p.entryId));
 return state.records.filter(r=>r.kind==='entry'&&r.cardId===cardId&&(ambiguous.has(r.id)||needsReview(r))).map(r=>({id:r.id,month:r.invoicePeriod||r.date.slice(0,7),description:r.description,type:ambiguous.has(r.id)?'installment':'review'})).sort((a,b)=>a.month.localeCompare(b.month)||a.id.localeCompare(b.id));
}
export function cardHeading(state,card){const n=cardPending(state,card.id).length;return `<div class="heading card-heading"><div><div class="eyebrow">HISTÓRICO DO CARTÃO</div><div class="card-title"><h1>${esc(card.name)}</h1>${btn(`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>${n?`<span class="notification-count" aria-hidden="true">${n}</span>`:''}`,'finance-notifications',`data-card="${esc(card.id)}" aria-label="Notificações de ${esc(card.name)}: ${n} pendência(s)" aria-haspopup="dialog"`,'notification-bell')}</div><p>Fechamento: dia ${card.closing||'não definido'} · Vencimento: dia ${card.due||'não definido'}</p></div><div class="row">${state.role==='owner'?btn('Nova compra','new-purchase',`data-card="${esc(card.id)}"`,'primary')+btn('Importar CSV','finance-import',`data-card="${esc(card.id)}"`):''}${btn('Todos os cartões','finance-back')}</div></div>`;}
export function openCardNotifications(state,cardId,onSelect){
 const opener=document.activeElement,items=cardPending(state,cardId),d=document.createElement('dialog');d.className='csv-dialog notification-panel';d.dataset.financialDialog='true';d.setAttribute('aria-labelledby','notification-title');
 d.innerHTML=`<div class="dialog-heading"><h2 id="notification-title">Pendências do cartão</h2><button type="button" data-close>Fechar</button></div>${items.length?['review','installment'].map(type=>{const rows=items.filter(r=>r.type===type);return rows.length?`<section><h3>${type==='review'?'Lançamentos a conferir':'Parcelas com vínculo ambíguo'} · ${rows.length}</h3>${rows.map(r=>`<button type="button" class="notification-item" data-target="${esc(r.id)}"><strong>${esc(r.description)}</strong><small>${esc(monthLabel(r.month))} · ${type==='review'?'Abrir lançamento':'Resolver vínculo'}</small></button>`).join('')}</section>`:'';}).join(''):'<p>Não há itens pendentes neste cartão.</p>'}<p class="tiny">Somente pendências ainda não resolvidas. Erros e duplicidades do CSV são tratados antes de salvar e não são recriados aqui.</p>`;
 document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>{d.remove();if(opener?.isConnected)opener.focus({preventScroll:true});},{once:true});d.onclick=e=>{const b=e.target.closest('[data-target]');if(!b)return;const item=items.find(r=>r.id===b.dataset.target);d.close();onSelect(item);};d.showModal();
}
export function revealCardPending(state,period,cardId,item,render){
 monthScope=cardId+'|'+period;activeMonth=item.month;calendarYear=item.month.slice(0,4);
 const rows=window.F.ledger(state.records).filter(r=>r.cardId===cardId&&r.date.startsWith(item.month));revealSavedRow('card:'+cardId+':'+item.month,rows,item.id);render();
 const node=[...document.querySelectorAll('[data-saved-id]')].find(n=>n.dataset.savedId===item.id);if(node){node.classList.add('gold-highlight');node.focus({preventScroll:true});node.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});setTimeout(()=>node.classList.remove('gold-highlight'),4000);}
}
function invoiceCalendar(months,monthRows,estimates,sum){
 const years=[...new Set(months.map(m=>m.slice(0,4)))].sort(),position=years.indexOf(calendarYear),labels=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
 return `<section class="panel invoice-calendar"><div class="calendar-year">${btn('‹','finance-calendar-year',`data-year="${esc(years[position-1]||'')}" ${position<=0?'disabled':''} aria-label="Ano anterior com faturas"`)}<strong>${esc(calendarYear)}</strong>${btn('›','finance-calendar-year',`data-year="${esc(years[position+1]||'')}" ${position>=years.length-1?'disabled':''} aria-label="Próximo ano com faturas"`)}</div><div class="calendar-month-grid" role="group" aria-label="Meses de ${esc(calendarYear)}">${labels.map((label,i)=>{const month=calendarYear+'-'+String(i+1).padStart(2,'0'),rows=monthRows(month),projected=estimates.filter(r=>r.period===month),available=months.includes(month),pending=rows.filter(r=>needsReview(r)).length;return `<button type="button" class="calendar-month ${month===activeMonth?'selected':''}" data-action="finance-month" data-month="${month}" aria-pressed="${month===activeMonth}" ${!available?'disabled':''}><strong>${label}</strong><span>${rows.length?money(sum(rows)):'Sem cobranças'}</span>${projected.length?`<small>Estimado: ${money(projected.reduce((n,r)=>n+r.amount,0))}</small>`:''}<small>${rows.length?rows.length+' registro(s)':''}${pending?' · '+pending+' pendente(s)':''}</small></button>`;}).join('')}</div><p class="tiny">Selecione um mês para abrir os lançamentos abaixo. Estimativas aparecem separadas dos valores cadastrados.</p></section>`;
}
function openDialog(title){const d=document.createElement('dialog');d.dataset.financialDialog='true';d.className='csv-dialog';d.innerHTML=`<div class="dialog-heading"><h2>${esc(title)}</h2><button data-close type="button">Fechar</button></div><form><div data-fields></div><p data-error role="alert"></p><button class="primary" type="submit">Confirmar</button></form>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
function submitDialog(d,deps,action,payload){let busy=false;d.addEventListener('cancel',e=>{if(busy)e.preventDefault();});d.querySelector('form').onsubmit=async e=>{e.preventDefault();e.stopPropagation();if(busy||!d.isConnected)return;try{const p=payload(e.currentTarget);busy=true;d.querySelectorAll('button').forEach(b=>b.disabled=true);await deps.call(action,p);if(!d.isConnected)return;d.close();await deps.refresh();deps.message('Alteração salva.');}catch(err){if(d.isConnected){d.querySelector('[data-error]').textContent=err.message;d.querySelectorAll('button').forEach(b=>b.disabled=false);}}finally{busy=false;}};}
export function categoryDialog(state,entry,deps){
 if(state.role!=='owner')throw Error('Somente o titular pode categorizar.');const categories=state.records.filter(c=>c.kind==='category'&&!c.archived&&c.type===entry.type),key=categoryKey(entry.description),similar=state.records.filter(r=>r.kind==='entry'&&!r.locked&&r.type===entry.type&&categoryKey(r.description)===key),d=openDialog('Categoria e próximas importações');
 d.querySelector('[data-fields]').innerHTML=`<p>${esc(entry.description)}</p><p>Estabelecimento: <strong>${esc(merchantName(entry.description))}</strong> · ${esc(window.F.TYPES[entry.type])}</p><label>Categoria<select name="categoryId">${categories.map(c=>`<option value="${esc(c.id)}" ${c.id===entry.categoryId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="csv-include"><input name="applyExisting" type="checkbox"> Aplicar aos ${similar.length} lançamentos semelhantes existentes, incluindo este.</label><label class="csv-include"><input name="remember" type="checkbox"> Usar esta categoria nas próximas importações deste estabelecimento e natureza.</label><p class="tiny">Sem marcar as opções, somente este lançamento será alterado.</p>`;
 submitDialog(d,deps,'category-apply',form=>({entryId:entry.id,categoryId:form.elements.categoryId.value,applyExisting:form.elements.applyExisting.checked,confirmExisting:form.elements.applyExisting.checked,remember:form.elements.remember.checked}));
}
export async function intelligenceAction(action,el,ctx,deps){
 if(action==='finance-month'){activeMonth=el.dataset.month;calendarYear=activeMonth.slice(0,4);ctx.render();document.querySelector('.calendar-month.selected')?.focus({preventScroll:true});return true;}
 if(action==='finance-calendar-year'){if(!/^\d{4}$/.test(el.dataset.year||''))return true;calendarYear=el.dataset.year;const cardId=monthScope.split('|')[0],available=[...new Set([ctx.period,...window.F.ledger(ctx.state.records).filter(r=>r.cardId===cardId).map(r=>r.date.slice(0,7)),...installmentEstimates(ctx.state.installmentPlans,ctx.state.records).filter(r=>r.cardId===cardId).map(r=>r.period)])].filter(m=>m.startsWith(calendarYear+'-')).sort();activeMonth=available.find(m=>m.slice(5)===activeMonth?.slice(5))||available[0]||ctx.period;ctx.render();document.querySelector('.calendar-month.selected')?.focus({preventScroll:true});return true;}
 if(!['finance-category','finance-rule-remove','finance-installment-edit','finance-installment-toggle','finance-installment-resolve'].includes(action))return false;
 const state=ctx.state;if(state.role!=='owner')throw Error('Somente o titular pode alterar os dados.');
 if(action==='finance-category'){const r=state.records.find(r=>r.id===el.dataset.id&&r.kind==='entry'&&!r.locked);if(!r)throw Error('Lançamento indisponível.');categoryDialog(state,r,deps);return true;}
 if(action==='finance-rule-remove'){if(confirm('Remover a regra das próximas importações? Os lançamentos atuais serão preservados.')){await deps.call('category-rule-remove',{key:el.dataset.key,type:el.dataset.type});await deps.refresh();}return true;}
 const plan=state.installmentPlans?.find(p=>p.id===el.dataset.plan);
 if(action==='finance-installment-toggle'){if(!plan)throw Error('Plano indisponível.');if(confirm('Alterar somente as previsões desta compra? As cobranças reais serão preservadas.')){await deps.call('installment-edit',{planId:plan.id,cancelPlan:el.dataset.cancel==='true'});await deps.refresh();}return true;}
 if(action==='finance-installment-edit'){if(!plan)throw Error('Plano indisponível.');const number=Number(el.dataset.number),part=expectedPart(plan,number),d=openDialog('Ajustar parcela estimada');d.querySelector('[data-fields]').innerHTML=`<p>${esc(plan.name)} · ${number}/${plan.total}</p><p class="estimate-notice">${warning}</p><label>Mês esperado<input type="month" name="period" value="${esc(part.period)}" required></label><label>Valor estimado (R$)<input name="amount" value="${(part.amount/100).toFixed(2).replace('.',',')}" required></label><label class="csv-include"><input name="cancelled" type="checkbox" ${part.cancelled?'checked':''}> Cancelar esta previsão</label>${plan.cancelled?'<p>O plano inteiro está cancelado. Reative as previsões da compra para voltar a exibi-las.</p>':''}`;submitDialog(d,deps,'installment-edit',f=>({planId:plan.id,number,period:f.elements.period.value,amount:cents(f.elements.amount.value),cancelled:f.elements.cancelled.checked}));return true;}
 const pending=state.installmentPending?.find(p=>p.entryId===el.dataset.id),entry=state.records.find(r=>r.id===el.dataset.id);if(!pending||!entry)throw Error('Correspondência indisponível.');const info=installmentInfo(entry.description),d=openDialog('Conferir cobrança e previsão');d.querySelector('[data-fields]').innerHTML=`<h3>${esc(entry.description)}</h3><p>Cobrança real: ${esc(entry.invoicePeriod)} · ${money(entry.amount)} · compra em ${date(entry.date)}</p><label>Esta cobrança corresponde a<select name="target" required><option value="">Escolha…</option>${pending.candidates.map(id=>{const p=state.installmentPlans.find(x=>x.id===id),part=expectedPart(p,info.number);return `<option value="${esc(id)}">${esc(p.name)} · previsão ${esc(part.period)} · ${money(part.amount)} · compra ${date(p.purchaseDate)}</option>`;}).join('')}<option value="new">Outra compra — criar suas previsões</option><option value="ignore">Manter somente a cobrança, sem gerar previsões</option></select></label><p class="tiny">Vincular substitui somente a parcela correspondente. As demais estimativas mantêm seus valores e meses até você ajustá-las.</p>`;submitDialog(d,deps,'installment-resolve',f=>({entryId:entry.id,confirm:true,mode:['new','ignore'].includes(f.elements.target.value)?f.elements.target.value:'link',planId:f.elements.target.value}));return true;
}
