import {esc,natureLabel} from './review-ui.js';
export function openNatureRules(state,deps){
 if(state.role!=='owner')throw Error('Somente o titular pode gerenciar regras pessoais.');
 const opener=document.activeElement,d=document.createElement('dialog');d.className='csv-dialog';d.dataset.financialDialog='true';d.setAttribute('aria-label','Regras pessoais de natureza');let busy=false;
 d.innerHTML=`<div class="dialog-heading"><h2>Regras pessoais de natureza</h2><button type="button" data-close>Fechar</button></div><p>Estas regras são privadas. Alterações afetam próximas importações e preservam lançamentos existentes. Crie novas regras durante a conferência de um CSV.</p>${(state.natureRules||[]).map((r,i)=>`<section class="bank-item"><strong>${esc(r.expression)}</strong><p>${esc(r.bank)} · ${esc(r.format)} · ${r.credit?'Cartão':'Conta'} · ${esc(natureLabel(r.type))}</p><p class="tiny">${esc(r.signConvention==='negative-credit'?'Negativo = crédito':r.signConvention==='positive-credit'?'Positivo = crédito':'Natureza manual')}</p><button type="button" data-edit-rule="${i}">Editar</button> <button type="button" class="danger" data-remove-rule="${i}">Remover</button></section>`).join('')||'<p>Nenhuma regra pessoal de natureza.</p>'}<div data-form></div><p data-error role="alert"></p>`;
 document.body.append(d);d.querySelector('[data-close]').onclick=()=>{if(!busy)d.close();};d.addEventListener('cancel',e=>{if(busy)e.preventDefault();});d.addEventListener('close',()=>{d.remove();if(opener?.isConnected)opener.focus();},{once:true});d.showModal();
 async function save(action,p){if(busy)return;busy=true;d.querySelectorAll('button').forEach(b=>b.disabled=true);try{await deps.call(action,p);d.close();await deps.refresh();deps.message('Regra pessoal atualizada. Os lançamentos existentes foram preservados.');}catch(e){d.querySelector('[data-error]').textContent=e.message;}finally{busy=false;d.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 d.onclick=e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.hasAttribute('data-remove-rule')){const rule=state.natureRules[+b.dataset.removeRule];if(confirm('Remover esta regra das próximas importações?'))save('nature-rule-remove',{id:rule.id});}if(b.hasAttribute('data-edit-rule')){const rule=state.natureRules[+b.dataset.editRule],types=rule.credit?['despesa','estorno','fatura']:['despesa','receita','transferencia','fatura','estorno','investimento','divida','saldo'];d.querySelector('[data-form]').innerHTML=`<form class="panel"><h3>Editar regra</h3><label>Expressão específica<input name="expression" maxlength="120" required value="${esc(rule.expression)}"></label><label>Natureza<select name="type">${types.map(t=>`<option value="${t}" ${t===rule.type?'selected':''}>${esc(natureLabel(t))}</option>`).join('')}</select></label><label class="csv-include"><input type="checkbox" name="confirm" required> Aplicar a regra somente nas próximas importações</label><button type="submit" class="primary">Salvar regra</button></form>`;const f=d.querySelector('form');f.elements.expression.focus();f.onsubmit=e=>{e.preventDefault();e.stopPropagation();save('nature-rule-save',{confirm:f.elements.confirm.checked,rule:{...rule,expression:f.elements.expression.value,type:f.elements.type.value}});};}};
}
