import {inferNature,natureToken,editedImportRow,duplicateIndex,analyzeDuplicates,natureLabel as identificationLabel} from './import-rules.mjs';
import {cents,validDate,suggestion,digest} from './csv-core.mjs';
import {categoryKey,merchantName,installmentInfo} from './intelligence.mjs';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((n||0)/100);
export const monthLabel=m=>/^\d{4}-\d{2}$/.test(m)?new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T12:00:00Z')):'Definir mês';
export function suggestFileMonth(name){const found=new Set();for(const match of name.matchAll(/(?:^|\D)((?:19|20|21)\d{2}|2200)[-_](0[1-9]|1[0-2])(?=\D|$)/g))found.add(match[1]+'-'+match[2]);const normalized=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const names=['janeiro','fevereiro','marco','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];names.forEach((month,i)=>{const match=normalized.match(new RegExp('(?:^|[^a-z])'+month+'[ _-]*(?:de[ _-]*)?((?:19|20|21)\\d{2}|2200)(?!\\d)'));if(match)found.add(match[1]+'-'+String(i+1).padStart(2,'0'));});return found.size===1?[...found][0]:'';}
export const dateLabel=s=>String(s||'').split('-').reverse().join('/');
export const nature=r=>r.reversal?'estorno':r.type;
export const natureLabel=t=>t==='estorno'?'Estornos':window.F.TYPES[t]||'Sem natureza';
export function totals(rows){const sums={};for(const r of rows){const t=nature(r);if(Number.isSafeInteger(r.amount))sums[t]=(sums[t]||0)+Math.abs(r.amount);}return Object.entries(sums).map(([t,n])=>`${esc(natureLabel(t))}: ${money(n)}`).join(' · ')||'Nenhum valor selecionado';}
export const filterOptions=[['all','Todos'],['issues','Pendências'],['duplicates','Duplicados'],['subscriptions','Assinaturas'],['installments','Parcelados']];
export async function mountImportReview({d,state,parsed,choices,batch,fields,classification,cardId,deps,alive,onSaving}){
 const target=d.querySelector('[data-review]');let filter='all',openMonth='',editing=-1,pages={},deferReview=false,confirmed=false,skip=false,saving=false,serverError=null,disabledBefore=[],confirmationDialog=null,comparisonDialog=null,assessmentVersion=0;
 const duplicateBase=duplicateIndex(state.records,window.F.ledger(state.records),state.imports||[]);
 const effective=(r,c)=>{let amount=null;try{amount=cents(c.amountText);}catch{}return editedImportRow(r,{...c,amount});};
 async function assess(initial=false){
  const version=++assessmentVersion,rows=parsed.map(r=>effective(r,choices[r.index])),checks=await analyzeDuplicates(rows,duplicateBase);
  const results=await Promise.all(rows.map(async(r,i)=>{const hint=inferNature(r,state.natureRules||[],state.records);return {check:checks[i],hint,duplicateToken:await digest(checks[i].signature),natureToken:await digest(natureToken(r,choices[i].type,hint))};}));
  if(version!==assessmentVersion||!alive())return false;
  for(const [i,result]of results.entries()){const r=parsed[i],c=choices[i];r.natureHint=result.hint;r.duplicateCheck=result.check;r.exact=result.check.exact;r.possible=result.check.possible;r.duplicateProof=result.duplicateToken;r.natureProof=result.natureToken;
   if(c.duplicateToken!==r.duplicateProof)c.acceptDuplicate=false;
   if(c.natureToken!==r.natureProof)c.natureConfirmed=false;
   if(r.exact||initial&&(r.possible||r.issues.length||!c.type||result.hint.needsConfirmation))c.include=false;
  }
  return true;
 }
 async function confirmNature(i,type){const c=choices[i];c.type=type;c.natureConfirmed=false;c.acceptDuplicate=false;const hint=suggestion({...parsed[i],...c},state.records,classification,state.categoryRules,state.catalog?.rules||[],state.recurringCandidates);Object.assign(c,hint,{manualCategory:false});confirmed=false;serverError=null;if(await assess()){c.natureConfirmed=true;c.natureToken=parsed[i].natureProof;render();target.querySelector(`[data-row-id="${i}"]`)?.focus({preventScroll:true});}}
 function closeComparison(){comparisonDialog?.close();}
 function showComparison(i){
  closeComparison();const r=parsed[i],c=choices[i],check=r.duplicateCheck,opener=document.activeElement,modal=document.createElement('dialog');comparisonDialog=modal;modal.className='csv-dialog duplicate-comparison';modal.dataset.financialDialog='true';modal.setAttribute('aria-labelledby','duplicate-heading');
  const detail=x=>{const label=x.cardId?state.records.find(v=>v.id===x.cardId)?.name:x.account,info=installmentInfo(x.description);return `<dl class="comparison-facts"><dt>Conta/cartão</dt><dd>${esc(label||'Não informado')}${x.bank?' · '+esc(x.bank):''}</dd><dt>Origem</dt><dd>${esc(x.fileName||x.csvFile||'Não registrada')}${Number.isInteger(x.originalIndex)?' · linha '+(x.originalIndex+2):x.csvRow?' · linha '+x.csvRow:''}</dd><dt>Data da compra/movimentação</dt><dd>${esc(dateLabel(x.originalDate||x.date))}</dd><dt>Mês da fatura</dt><dd>${esc(x.invoicePeriod?monthLabel(x.invoicePeriod):'Não se aplica')}</dd><dt>Descrição</dt><dd>${esc(x.description)}</dd><dt>Natureza</dt><dd>${esc(natureLabel(nature(x)))}</dd><dt>Valor</dt><dd>${money(Math.abs(x.amount))}</dd><dt>Parcela</dt><dd>${info?info.number+'/'+info.total:'Não identificada'}</dd>${x.csvOriginal||x.rawAmount?`<dt>Valor na origem</dt><dd>${esc(x.csvOriginal?.amount||x.rawAmount)}</dd>`:''}</dl>`;};
  modal.innerHTML=`<div class="dialog-heading"><h2 id="duplicate-heading">${check.exact?'Reimportação identificada':'Comparar possíveis duplicados'}</h2><button type="button" data-close-comparison>Fechar</button></div><p>${esc(check.reason)}</p><div class="comparison-grid"><section><h3>Novo lançamento</h3>${detail(effective(r,c))}</section><section><h3>Candidatos encontrados · ${check.candidateCount}</h3>${check.candidates.slice(0,20).map(m=>`<article class="bank-item">${detail(m.row)}<p class="tiny">${esc(m.reason)}</p></article>`).join('')}${check.candidateCount>20?'<p>Exibindo os primeiros 20 candidatos. A proteção considera todas as correspondências.</p>':''}</section></div><p data-comparison-error role="alert"></p><div class="row"><button type="button" data-skip-duplicate>É duplicado — não importar</button>${!check.exact?'<button type="button" class="primary" data-distinct>São movimentações diferentes — importar</button>':''}</div>`;
  d.append(modal);modal.addEventListener('close',()=>{if(comparisonDialog===modal)comparisonDialog=null;modal.remove();(opener?.isConnected?opener:target.querySelector(`[data-row-id="${i}"]`))?.focus({preventScroll:true});},{once:true});modal.onclick=async e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();if(b.hasAttribute('data-close-comparison')){modal.close();return;}if(b.hasAttribute('data-skip-duplicate')){c.include=false;c.duplicateDecision='skip';c.acceptDuplicate=false;confirmed=false;modal.close();render();return;}if(b.hasAttribute('data-distinct')){const previous=r.duplicateProof;b.disabled=true;if(!await assess())return;if(r.exact||r.duplicateProof!==previous){modal.querySelector('[data-comparison-error]').textContent='Os dados mudaram. Feche e reabra a comparação.';return;}c.include=true;c.acceptDuplicate=true;c.duplicateToken=r.duplicateProof;c.duplicateDecision='distinct';confirmed=false;modal.close();render();}};modal.showModal();
 }
 d.addEventListener('close',()=>{assessmentVersion++;closeComparison();},{once:true});
 await assess(true);
 const category=c=>c.categoryId?state.records.find(r=>r.id===c.categoryId)?.name:c.categoryName;
 const month=r=>cardId?r.invoicePeriod:(validDate(choices[r.index].date)?choices[r.index].date.slice(0,7):'');
 const months=()=>[...new Set(parsed.map(month))].sort();
 function issue(r){const c=choices[r.index];if(r.exact)return null;
  if(!validDate(c.date))return {field:'date',message:'Informe uma data válida.'};
  if(!c.description.trim()||c.description.length>2000)return {field:'description',message:'Revise a descrição (até 2.000 caracteres).'};
  try{if(cents(c.amountText)<=0)throw Error();}catch{return {field:'amountText',message:'Informe um valor positivo válido.'};}
  if(!c.type)return {field:'type',message:'Escolha a natureza.'};
  if((r.natureHint?.needsConfirmation||r.natureHint?.type!==c.type||c.rememberNature)&&!c.natureConfirmed)return {field:'type',message:'Confirme a natureza desta linha.'};
  if(c.rememberNature&&(!c.natureExpression||c.natureExpression.trim().length<6||c.natureExpression.trim().split(/\s+/).length<2))return {field:'natureExpression',message:'Use uma expressão específica com pelo menos duas palavras.'};
  if(c.type!=='transferencia'&&!c.categoryId&&(!c.categoryName.trim()||c.categoryName.trim().length>80))return {field:'categoryName',message:'Informe uma categoria de até 80 caracteres.'};
  if(r.issues.length&&!c.acceptCorrection)return {field:'acceptCorrection',message:'Confirme a correção dos problemas de origem.'};
  if(r.possible&&!c.acceptDuplicate)return {field:'acceptDuplicate',message:'Confira a possível duplicidade.'};
  return null;
 }
 const matches=r=>filter==='all'||filter==='issues'&&Boolean(issue(r))||filter==='duplicates'&&(r.exact||r.possible)||filter==='subscriptions'&&category(choices[r.index])?.toLowerCase()==='assinaturas'||filter==='installments'&&Boolean(installmentInfo(choices[r.index].description));
 const sumRows=rows=>rows.filter(r=>choices[r.index].include).map(r=>{const c=choices[r.index];let amount;try{amount=cents(c.amountText);}catch{}return {...c,amount};});
 openMonth=months().find(m=>parsed.some(r=>month(r)===m&&issue(r)))??months().at(-1)??'';
 function row(r){const c=choices[r.index],problem=issue(r),part=installmentInfo(c.description);return `<div class="compact-record ${r.exact?'is-duplicate':''}" data-row-id="${r.index}" tabindex="-1"><div class="compact-line"><label class="compact-select"><input type="checkbox" data-include="${r.index}" aria-label="Importar linha ${r.originalIndex+2} de ${esc(r.fileName)}" ${c.include?'checked':''} ${r.exact?'disabled':''}></label><span class="compact-date">${dateLabel(c.date)||'Sem data'}</span><span class="compact-description">${esc(c.description)||'Sem descrição'}<small>${esc(c.merchant||merchantName(c.description))}</small></span><span class="compact-secondary">${esc(natureLabel(c.type))}</span><span class="compact-secondary">${esc(category(c)||'—')}</span><strong class="compact-value">${esc(c.amountText)} <small>R$</small></strong><button type="button" class="small" data-edit-row="${r.index}">${editing===r.index?'Recolher':'Editar'}</button></div><div class="compact-flags">${r.exact?`<button type="button" class="small" data-compare="${r.index}">Reimportação identificada — ver motivo</button>`:''}${problem?`<button type="button" class="error-link" data-error-row="${r.index}" data-error-field="${problem.field}">${esc(problem.message)}</button>`:''}${c.suggestionSource&&c.suggestionSource!=='default'?`<span class="tiny muted">${esc(({personal:'Regra pessoal',catalog:'Catálogo',recurrence:'Padrão de recorrência',manual:'Escolha manual'})[c.suggestionSource]||'')}</span>`:''}${r.subscription?'<span class="tag">Possível assinatura — confirmar</span>':''}${r.possible?`<button type="button" class="small" data-compare="${r.index}">${c.acceptDuplicate?'Duplicidade conferida':'Comparar possível duplicado'}</button>`:''}${category(c)?.toLowerCase()==='assinaturas'?'<span class="tag">Assinatura sugerida</span>':''}${part?`<span class="tag">Parcela ${part.number}/${part.total}</span>`:''}<span class="tag">${esc(identificationLabel(r,c,r.natureHint))}</span><span class="tiny">${esc(r.natureHint.reason)}${r.natureHint.evidence?' Há cobrança anterior compatível, inclusive para estorno parcial; nenhum vínculo foi criado.':''}</span>${!r.exact&&(r.natureHint.needsConfirmation||!c.type||c.rememberNature)&&!c.natureConfirmed?`<div class="row nature-choices">${r.cardId?`<button type="button" data-nature-index="${r.index}" data-nature-type="estorno">É estorno</button><button type="button" data-nature-index="${r.index}" data-nature-type="fatura">É pagamento da fatura</button>`:''}${c.type?`<button type="button" data-nature-index="${r.index}" data-nature-type="${esc(c.type)}">Confirmar: ${esc(natureLabel(c.type))}</button>`:''}</div>`:''}</div>${editing===r.index?`<div class="compact-editor">${fields(r)}</div>`:''}</div>`;}
 function render(){if(!d.isConnected)return;const selected=parsed.filter(r=>choices[r.index].include),errors=parsed.filter(r=>issue(r)),blocking=selected.filter(r=>issue(r));
 target.innerHTML=`<h3>Conferir movimentações por mês</h3><p class="tiny">Os filtros não alteram a seleção. Pagamentos de fatura e transferências ficam fora das despesas.</p><div class="review-filters">${filterOptions.map(([key,label])=>`<button type="button" data-review-filter="${key}" aria-pressed="${key===filter}" class="small ${key===filter?'primary':''}">${label}</button>`).join('')}</div>${errors.length?`<details class="review-errors"><summary>${errors.length} linha(s) com pendências · clique para localizar</summary>${errors.slice(0,100).map(r=>{const p=issue(r);return `<button type="button" class="error-link" data-error-row="${r.index}" data-error-field="${p.field}">${esc(r.fileName)} · linha ${r.originalIndex+2}: ${esc(p.message)}</button>`;}).join('')}${errors.length>100?'<p>Use o filtro Pendências para consultar todas as linhas.</p>':''}</details>`:''}${months().map(m=>{const all=parsed.filter(r=>month(r)===m),visible=all.filter(matches),pending=all.filter(r=>issue(r)).length,page=Math.min(pages[m]||0,Math.max(0,Math.ceil(visible.length/25)-1));pages[m]=page;return `<section class="review-month"><button type="button" class="month-heading" data-month="${esc(m)}" aria-expanded="${m===openMonth}">${m===openMonth?'▾':'▸'} ${esc(monthLabel(m))} · ${all.length} lançamento(s) · ${pending} pendente(s)</button>${m===openMonth?`<p class="tiny">${totals(sumRows(all))}</p><div class="row"><button type="button" class="small" data-select-month="${esc(m)}">Selecionar disponíveis do mês</button><button type="button" class="small" data-unselect-month="${esc(m)}">Desmarcar mês</button></div><div class="compact-head"><span>Importar</span><span>Data</span><span>Descrição</span><span>Natureza</span><span>Categoria</span><span>Valor</span><span>Ação</span></div>${visible.slice(page*25,(page+1)*25).map(row).join('')||'<p>Nenhum lançamento neste filtro.</p>'}<div class="pagination"><button type="button" data-page="${page-1}" ${!page?'disabled':''}>Anterior</button><span>${page+1} / ${Math.max(1,Math.ceil(visible.length/25))}</span><button type="button" data-page="${page+1}" ${(page+1)*25>=visible.length?'disabled':''}>Próxima</button></div>`:''}</section>`;}).join('')}<footer class="import-footer import-footer-compact"><span role="status">${selected.length} selecionado(s) · ${blocking.length?'⚠ '+blocking.length+' pendência(s)':'Sem pendências selecionadas'}</span><button type="button" class="primary" data-continue>Continuar importação</button></footer><div data-commit-error role="alert">${serverError?errorHTML(serverError):''}</div>`;
 }
 function closeConfirmation(){if(!confirmationDialog)return;const modal=confirmationDialog;confirmationDialog=null;modal.close();modal.remove();}
 function renderConfirmation(){if(!confirmationDialog)return;const selected=parsed.filter(r=>choices[r.index].include),excluded=parsed.filter(r=>r.issues.length&&!choices[r.index].include).length;
  confirmationDialog.innerHTML=`<div class="dialog-heading"><h2 id="import-final-title">Confirmar importação</h2><button type="button" data-return aria-label="Voltar à lista">Fechar</button></div><p>${selected.length} lançamento(s) selecionado(s) de ${parsed.length}. ${parsed.length-selected.length} não serão importados.</p><p class="tiny">Reimportações bloqueadas: ${parsed.filter(r=>r.exact).length} · Possíveis duplicados desmarcados: ${parsed.filter(r=>r.possible&&!choices[r.index].include).length}. Volte à lista para alterar a seleção.</p><p class="notice">${totals(sumRows(parsed))}</p><label class="csv-include"><input type="checkbox" data-defer ${deferReview?'checked':''}> Importar agora e conferir depois</label><p class="tiny">Os lançamentos válidos serão salvos para organizar depois. Parcelas identificadas dispensam conferência individual; os demais ficam pendentes.</p>${!deferReview?`<label class="csv-include"><input type="checkbox" data-confirm ${confirmed?'checked':''}> Conferi as linhas selecionadas e desejo adicioná-las.</label>`:''}${excluded?`<label class="csv-include"><input type="checkbox" data-skip ${skip?'checked':''}> Autorizo continuar sem ${excluded} linha(s) com problemas que deixei desmarcadas.</label>`:''}<div data-final-error role="alert">${serverError?errorHTML(serverError):''}</div><div class="row"><button type="button" data-return>Voltar à lista</button><button type="button" class="primary" data-commit>${deferReview?'Importar e conferir depois':'Confirmar e importar'}</button></div>`;
 }
 function openConfirmation(){if(confirmationDialog)return;confirmationDialog=document.createElement('dialog');confirmationDialog.className='csv-dialog import-confirmation';confirmationDialog.dataset.financialDialog='true';confirmationDialog.setAttribute('aria-labelledby','import-final-title');d.append(confirmationDialog);confirmationDialog.onclick=target.onclick;confirmationDialog.onchange=target.onchange;confirmationDialog.addEventListener('cancel',e=>{e.preventDefault();if(!saving)closeConfirmation();});renderConfirmation();confirmationDialog.showModal();}
 d.addEventListener('close',closeConfirmation,{once:true});
 function errorHTML(e){return Number.isInteger(e.index)?`<button type="button" class="error-link" data-error-row="${e.index}" data-error-field="${esc(e.field||'')}">${esc(e.message)}</button>`:esc(e.message);}
 function jump(index,field){closeConfirmation();const r=parsed[index];if(!r)return;filter='all';openMonth=month(r);editing=index;pages[openMonth]=Math.floor(parsed.filter(x=>month(x)===openMonth).findIndex(x=>x.index===index)/25);render();const node=target.querySelector(`[data-row-id="${index}"]`);node?.classList.add('gold-highlight');const focus=field?node?.querySelector(`[data-field="${field}"]`):null;(focus||node)?.focus({preventScroll:true});node?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});setTimeout(()=>node?.classList.remove('gold-highlight'),4000);}
 target.onclick=async event=>{const button=event.target.closest('button');if(!button||saving)return;
  if(button.hasAttribute('data-compare')){if(await assess())showComparison(Number(button.dataset.compare));return;}
  if(button.hasAttribute('data-nature-index')){await confirmNature(Number(button.dataset.natureIndex),button.dataset.natureType);return;}
  if(button.hasAttribute('data-return')){closeConfirmation();target.querySelector('[data-continue]')?.focus({preventScroll:true});return;}
  if(button.hasAttribute('data-continue')){if(!await assess())return;serverError=null;const selected=parsed.filter(r=>choices[r.index].include);if(!selected.length){serverError={message:'Selecione ao menos uma movimentação.'};render();return;}const invalid=selected.find(r=>issue(r));if(invalid){jump(invalid.index,issue(invalid).field);return;}openConfirmation();return;}
  if(button.hasAttribute('data-error-row')){jump(Number(button.dataset.errorRow),button.dataset.errorField);return;}
  if(button.hasAttribute('data-month')){openMonth=openMonth===button.dataset.month?null:button.dataset.month;render();return;}
  if(button.dataset.reviewFilter){filter=button.dataset.reviewFilter;pages={};openMonth=months().find(m=>parsed.some(r=>month(r)===m&&matches(r)))??openMonth;render();return;}
  if(button.hasAttribute('data-page')){pages[openMonth]=Number(button.dataset.page);render();return;}
  if(button.hasAttribute('data-edit-row')){const i=Number(button.dataset.editRow);editing=editing===i?-1:i;render();return;}
  if(button.hasAttribute('data-select-month')||button.hasAttribute('data-unselect-month')){const on=button.hasAttribute('data-select-month'),m=on?button.dataset.selectMonth:button.dataset.unselectMonth;for(const r of parsed)if(month(r)===m&&!r.exact&&(!on||!issue(r)))choices[r.index].include=on;confirmed=false;render();return;}
  if(button.hasAttribute('data-apply-category')){const c=choices[Number(button.dataset.applyCategory)];for(const r of parsed)if(!r.exact&&choices[r.index].type===c.type&&categoryKey(choices[r.index].description)===categoryKey(c.description)){choices[r.index].categoryId=c.categoryId;choices[r.index].categoryName=c.categoryName;choices[r.index].manualCategory=true;choices[r.index].suggestionSource='manual';}confirmed=false;serverError=null;render();return;}
  if(!button.hasAttribute('data-commit')||!confirmationDialog)return;
  serverError=null;
  try{if(!alive())throw Error('A conta mudou. Abra a importação novamente.');if(!await assess())return;
   const selected=parsed.filter(r=>choices[r.index].include);if(!selected.length)throw Error('Selecione ao menos uma movimentação.');
   const invalid=selected.find(r=>issue(r));if(invalid)throw Object.assign(Error(`${invalid.fileName} · linha ${invalid.originalIndex+2}: ${issue(invalid).message}`),{index:invalid.index,field:issue(invalid).field});
   if(!deferReview&&!confirmed)throw Error('Marque a confirmação após conferir os lançamentos.');
   if(parsed.some(r=>r.issues.length&&!choices[r.index].include)&&!skip)throw Error('Autorize continuar sem as linhas com problemas desmarcadas.');
   saving=true;onSaving(true);disabledBefore=[...d.querySelectorAll('button,input,select')].map(x=>[x,x.disabled]);disabledBefore.forEach(([x])=>x.disabled=true);
   const files=batch.map((file,fileIndex)=>({...file,decisions:parsed.filter(r=>r.fileIndex===fileIndex).map(r=>{const c=choices[r.index];return {index:r.originalIndex,include:c.include,date:c.date,description:c.description,type:c.type,amount:effective(r,c).amount,categoryId:c.categoryId,categoryName:c.categoryName,manualCategory:c.manualCategory,acceptCorrection:c.acceptCorrection,acceptDuplicate:c.acceptDuplicate,duplicateToken:c.duplicateToken,duplicateDecision:c.duplicateDecision,natureConfirmed:c.natureConfirmed,natureToken:c.natureToken,rememberNature:c.rememberNature,natureExpression:c.natureExpression,rememberRule:c.rememberRule};})}));
   const result=await deps.call('csv-batch',{files,protocol:3,confirm:true,acceptSkipped:skip,deferReview,catalogRefs:(state.catalog?.rules||[]).map(r=>({rule_id:r.rule_id,version:r.version}))});if(!alive())return;closeConfirmation();d.close();await deps.refresh();deps.message(`${result.count} movimentação(ões) adicionada(s)${deferReview?' — conferência posterior':''}.${result.catalogUnavailable?' Catálogo indisponível; suas categorias escolhidas foram preservadas.':''}`);
  }catch(e){if(!d.isConnected)return;const loc=e.importLocation,r=loc&&parsed.find(r=>r.fileIndex===loc.fileIndex&&r.originalIndex===loc.rowIndex);serverError={message:e.message,index:r?.index??e.index,field:loc?.field||e.field};disabledBefore.forEach(([x,disabled])=>{if(x.isConnected)x.disabled=disabled;});render();renderConfirmation();(confirmationDialog?.querySelector('[data-final-error]')||target.querySelector('[data-commit-error]'))?.scrollIntoView({block:'nearest'});}finally{saving=false;onSaving(false);}
 };
 function record(input){const container=input.closest('[data-index]'),field=input.dataset.field;if(!container||!field)return null;const index=Number(container.dataset.index),c=choices[index];if(parsed[index].exact)return null;const next=input.type==='checkbox'?input.checked:input.value;if(c[field]!==next)assessmentVersion++;if(c[field]!==next&&['date','description','amountText','type'].includes(field)){c.natureConfirmed=false;c.acceptDuplicate=false;c.acceptCorrection=false;}c[field]=next;if(['categoryId','categoryName'].includes(field)){c.manualCategory=true;c.suggestionSource='manual';}confirmed=false;serverError=null;return {index,c,field};}
 target.oninput=event=>{if(saving)return;record(event.target);};
 target.onchange=async event=>{if(saving)return;const input=event.target;
  if(input.hasAttribute('data-defer')){deferReview=input.checked;confirmed=false;renderConfirmation();confirmationDialog?.querySelector('[data-defer]')?.focus({preventScroll:true});return;}
  if(input.hasAttribute('data-confirm')){confirmed=input.checked;return;}
  if(input.hasAttribute('data-skip')){skip=input.checked;return;}
  if(input.hasAttribute('data-include')){choices[Number(input.dataset.include)].include=input.checked;confirmed=false;serverError=null;render();return;}
  const changed=record(input);if(!changed)return;const {index,c,field}=changed;
  if(field==='type'||field==='description'){const hint=suggestion({...parsed[index],...c},state.records,classification,state.categoryRules,state.catalog?.rules||[],state.recurringCandidates);if(field==='type'||!c.manualCategory)Object.assign(c,hint,{manualCategory:false});else c.merchant=hint.merchant;parsed[index].subscription=hint.possibleSubscription;}
  if(['date','description','amountText','type'].includes(field)){openMonth=month(parsed[index]);if(!await assess())return;if(field==='type'&&c.type){c.natureConfirmed=true;c.natureToken=parsed[index].natureProof;}}
  if(field==='rememberNature'&&c.rememberNature)c.natureConfirmed=false;
  render();
 };
 render();
}
