'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BRL=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((n||0)/100),num=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(n||0),dateBR=s=>s?s.split('-').reverse().join('/'):'Sem prazo';
const today=()=>{const d=new Date();return F.date(d.getFullYear(),d.getMonth()+1,d.getDate());};
const icons={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z',list:'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',chart:'M4 20V10M10 20V4M16 20v-7M22 20H2',wallet:'M3 6h16v14H3zM3 6V3h13v3M15 11h6v5h-6z',target:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18M12 7a5 5 0 1 0 0 10 5 5 0 1 0 0-10M12 11v2',shield:'M12 3 3 6v6c0 5 9 9 9 9s9-4 9-9V6zM8 12l3 3 5-6',card:'M3 5h18v14H3zM3 10h18M6 15h4',trend:'M3 17l6-6 4 4 8-10M15 5h6v6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',plus:'M12 5v14M5 12h14',arrow:'M7 17 17 7M7 7h10v10',down:'M7 7l10 10M7 17h10V7',menu:'M4 6h16M4 12h16M4 18h16',sun:'M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8',tag:'M3 3h8l10 10-8 8L3 11zM7 7h.01',check:'M5 12l4 4L19 6',download:'M12 3v12M7 10l5 5 5-5M4 16v5h16v-5',star:'m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z'};
function icon(name,size=18){return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.list}"/></svg>`;}
const routes=[['dashboard','Visão geral','home','SEU DINHEIRO'],['entries','Lançamentos','list'],['budget','Orçamento','wallet'],['cards','Cartões','card'],['debts','Dívidas','trend'],['bills','Contas a pagar','list'],['annual','Resumo anual','chart'],['goals','Metas financeiras','target','SEU FUTURO'],['reserve','Reserva ideal','shield'],['assets','Patrimônio','chart'],['simulator','Simulador','settings'],['achievements','Conquistas','star'],['wishes','Lista de desejos','tag'],['categories','Categorias','tag','ORGANIZAÇÃO'],['import','Importar planilha','download'],['settings','Dados e preferências','settings']];
let state={records:[],settings:{}},route='dashboard',period=today().slice(0,7),query='',sort='date-desc',filter='',page=0,chosenFile='',importPlan=null,importOptions={year:'',useGoalList:false,cardSource:'monthly'},busy=false;
const rec=kind=>state.records.filter(r=>r.kind===kind),byId=id=>state.records.find(r=>r.id===id),catName=id=>byId(id)?.name||'Sem categoria';
const api=(action,payload)=>window.norte.call(action,payload);
async function refresh(){state=await api('state');document.body.classList.toggle('light',state.settings.theme==='light');render();}
function toast(text,error=false){const t=$('#toast');t.textContent=text;t.style.display='block';t.style.background=error?'var(--red)':'var(--accent)';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',6000);}
function button(label,action,extra='',cls=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function empty(title,desc,action,label){return `<div class="empty"><div class="empty-icon">${icon('wallet',23)}</div><h2>${title}</h2><p>${desc}</p>${action?button(label,action,'','primary'):''}</div>`;}
function stat(label,value,foot,ic='chart',feature=false){return `<div class="stat ${feature?'feature':''}"><div class="stat-top"><span>${label}</span>${icon(ic,17)}</div><div class="stat-value">${BRL(value)}</div><div class="stat-foot ${feature?'muted':''}">${foot}</div></div>`;}
function header(title,sub,action='',label=''){return `<div class="heading"><div><div class="eyebrow">FINANÇAS COM DIREÇÃO</div><h1>${title}</h1><p>${sub}</p></div>${action?button(icon('plus')+' '+label,action,'','primary'):''}</div>`;}
function progress(value){return `<div class="track"><div style="width:${Math.max(0,Math.min(100,value||0))}%"></div></div>`;}
function actions(r){return button('Editar','edit',`data-id="${esc(r.id)}"`,'small flat')+button('Excluir','delete',`data-id="${esc(r.id)}"`,'small flat danger');}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function render(){const m=+period.slice(5),y=period.slice(0,4);$('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="mark">${icon('trend',25)}</div><div><strong>NORTE</strong><small>FINANÇAS PESSOAIS</small></div></div><nav aria-label="Menu principal">${routes.map(([id,label,ic,section])=>`${section?`<div class="nav-label">${section}</div>`:''}<button class="nav ${route===id?'active':''}" data-action="navigate" data-route="${id}" title="${label}" ${route===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('')}</nav><div class="offline"><span class="dot"></span>Seus dados, no seu computador.<br>Modo offline · v1.0.0</div></aside><main class="main"><div class="topbar"><div class="row">${button(icon('menu'),'collapse','aria-label="Recolher ou expandir menu"','flat')}<span class="breadcrumb">Pessoal &nbsp; / &nbsp; ${routes.find(r=>r[0]===route)?.[1]}</span></div><div class="top-actions"><select id="month" aria-label="Mês">${F.MONTHS.map((n,i)=>`<option value="${i+1}" ${i+1===m?'selected':''}>${n}</option>`).join('')}</select><input id="year" aria-label="Ano" type="number" min="1900" max="2200" value="${y}">${button(icon('sun'),'theme','aria-label="Alternar tema"','flat')}<div class="avatar" title="Conta local">EU</div></div></div><div class="content" id="content">${views[route]()}</div></main></div>`;}
function chart(){const entries=F.ledger(state.records),values=F.MONTHS.map((_,i)=>F.summarize(entries,period.slice(0,4)+'-'+String(i+1).padStart(2,'0'))),max=Math.max(1,...values.flatMap(x=>[x.income,x.totalOut]));return `<div class="chart" role="img" aria-label="Receitas e saídas mensais; valores detalhados no resumo anual">${values.map((v,i)=>`<div class="chart-month" title="${F.MONTHS[i]}: receitas ${BRL(v.income)}; saídas ${BRL(v.totalOut)}"><div class="chart-bar" style="height:${v.income/max*100}%"></div><div class="chart-bar out" style="height:${v.totalOut/max*100}%"></div><span>${F.MONTHS[i]}</span></div>`).join('')}</div>`;}
function entryTable(entries,limit){const rows=entries.slice(0,limit||entries.length);return table(['Data','Descrição','Categoria','Natureza','Valor',''],rows.map(e=>`<tr><td>${dateBR(e.date)}</td><td class="description">${esc(e.description)}${e.derived?'<br><span class="tiny muted">Parcela de cartão</span>':''}</td><td>${esc(catName(e.categoryId))}</td><td><span class="tag">${F.TYPES[e.type]}</span></td><td class="money ${e.type==='receita'?'positive':''}">${BRL(e.amount)}</td><td class="actions">${e.derived?button('Ver compra','edit',`data-id="${e.purchaseId}"`,'small flat'):e.locked?'<span class="read-only">Vinculado à dívida</span>':actions(e)}</td></tr>`));}
const views={
dashboard(){const entries=F.ledger(state.records),s=F.summarize(entries,period),recent=entries.filter(x=>x.date.startsWith(period)).sort((a,b)=>b.date.localeCompare(a.date));const groups={};recent.filter(x=>x.type==='despesa').forEach(x=>{const name=byId(x.categoryId)?.group||'Outros';groups[name]=(groups[name]||0)+x.amount;});const groupsSorted=Object.entries(groups).sort((a,b)=>b[1]-a[1]).slice(0,5);return header('Seu dinheiro, em perspectiva.','Um olhar claro sobre o mês e os próximos passos.','new-entry','Novo lançamento')+`<div class="cards">${stat('Saldo do período',s.balance,'Entradas − saídas e alocações','wallet',true)}${stat('Receitas',s.income,'Recebimentos no mês','arrow')}${stat('Despesas',s.expense,'Inclui parcelas de cartões','down')}${stat('Investimentos e dívidas',s.investment+s.debt,'Alocações registradas no mês','target')}</div><div class="two-col"><section class="panel"><div class="panel-head"><div><h2>Ritmo do ano</h2><span class="tiny muted">Receitas e saídas · ${period.slice(0,4)}</span></div><div class="legend"><span><i></i>Receitas</span><span><i class="out"></i>Saídas</span></div></div>${chart()}<div class="export-note">${button('Explorar resumo anual →','navigate','data-route="annual"','small flat')}</div></section><section class="panel"><div class="panel-head"><h2>Para onde vai o dinheiro</h2><span class="tag">${F.MONTHS[+period.slice(5)-1]}</span></div>${groupsSorted.length?groupsSorted.map(([g,v])=>`<div class="bar-row"><div class="bar-label"><span>${esc(g)}</span><span>${BRL(v)}</span></div>${progress(v/s.expense*100)}</div>`).join(''):empty('Tudo pronto para começar','Suas despesas aparecerão aqui conforme você registrar os lançamentos.','','')}</section></div><section class="panel"><div class="panel-head"><div><h2>Últimos movimentos</h2><span class="tiny muted">${recent.length} registros neste mês</span></div>${button('Ver todos →','navigate','data-route="entries"','small flat')}</div>${recent.length?entryTable(recent,5):empty('Seu mês começa aqui','Importe sua planilha ou registre sua primeira receita ou despesa.','navigate-import','Importar planilha')}</section><div class="notice">O saldo considera as parcelas no mês do vencimento. Transferências e pagamentos de faturas já detalhadas não geram outra despesa. O saldo inicial é informado em Lançamentos.</div>`;},
entries(){let entries=F.ledger(state.records).filter(x=>x.date.startsWith(period)&&(!filter||x.type===filter)&&normText(x.description+' '+catName(x.categoryId)).includes(normText(query)));entries.sort((a,b)=>sort==='amount-desc'?b.amount-a.amount:sort==='date-asc'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));const total=entries.length;page=Math.min(page,Math.max(0,Math.ceil(total/30)-1));return header('Lançamentos','Receitas, despesas e alocações em um só lugar.','new-entry','Novo lançamento')+`<section class="panel"><div class="toolbar"><input id="search" placeholder="Buscar descrição ou categoria…" aria-label="Buscar lançamentos" value="${esc(query)}"><select id="type-filter" aria-label="Filtrar natureza"><option value="">Todas as naturezas</option>${Object.entries(F.TYPES).map(([k,v])=>`<option value="${k}" ${filter===k?'selected':''}>${v}</option>`).join('')}</select><select id="sort" aria-label="Ordenação"><option value="date-desc" ${sort==='date-desc'?'selected':''}>Mais recentes</option><option value="date-asc" ${sort==='date-asc'?'selected':''}>Mais antigos</option><option value="amount-desc" ${sort==='amount-desc'?'selected':''}>Maior valor</option></select>${button('Exportar CSV','csv','','small')}</div>${total?entryTable(entries.slice(page*30,(page+1)*30)):empty('Nenhum lançamento encontrado','Altere os filtros ou adicione um lançamento.','','')}<div class="pagination"><span>${total} registros · ${BRL(entries.reduce((a,x)=>a+x.amount,0))} em valores registrados</span><div class="row">${button('Anterior','prev-page',page===0?'disabled':'','small')}<span>${page+1} / ${Math.max(1,Math.ceil(total/30))}</span>${button('Próxima','next-page',(page+1)*30>=total?'disabled':'','small')}</div></div></section>`;},
annual(){const entries=F.ledger(state.records),year=period.slice(0,4),s=F.summarize(entries,year);return header('Resumo anual',`O que entrou, saiu e foi destinado ao seu futuro em ${year}.`)+`<div class="cards">${stat('Receitas do ano',s.income,'Exclui saldos trazidos')}${stat('Despesas do ano',s.expense,'Compras e parcelas')}${stat('Alocações',s.investment+s.debt,'Investimentos e dívidas')}${stat('Resultado + saldos iniciais',s.balance,'Soma dos períodos','wallet',true)}</div><section class="panel">${chart()}</section><section class="panel">${table(['Mês','Receitas','Despesas','Investimentos','Dívidas','Saldo inicial','Resultado'],F.MONTHS.map((m,i)=>{const x=F.summarize(entries,year+'-'+String(i+1).padStart(2,'0'));return `<tr><td>${m}</td>${['income','expense','investment','debt','opening','balance'].map(k=>`<td class="money">${BRL(x[k])}</td>`).join('')}</tr>`;}))}</section>`;},
budget(){const actual=F.ledger(state.records).filter(x=>x.date.startsWith(period));const budgets=rec('budget').filter(x=>x.period===period);const ids=[...new Set([...budgets.map(x=>x.categoryId),...actual.map(x=>x.categoryId).filter(Boolean)])];return header('Orçamento','Planeje por categoria e acompanhe o realizado no mês.','new-budget','Planejar categoria')+`<section class="panel">${ids.length?table(['Categoria','Grupo','Previsto','Realizado','Diferença',''],ids.map(id=>{const b=budgets.find(x=>x.categoryId===id),v=actual.filter(x=>x.categoryId===id).reduce((a,x)=>a+x.amount,0),diff=(b?.amount||0)-v;return `<tr><td>${esc(catName(id))}</td><td>${esc(byId(id)?.group)}</td><td class="money">${BRL(b?.amount)}</td><td class="money">${BRL(v)}</td><td class="money">${BRL(diff)}</td><td class="actions">${b?actions(b):button('Planejar','new-budget',`data-category="${id}"`,'small flat')}</td></tr>`;})):empty('Dê um destino ao seu dinheiro','Defina um valor previsto para cada categoria do mês.','new-budget','Planejar categoria')}</section><div class="notice">Diferença = previsto − realizado. Categorias de receita, despesa e investimento mantêm suas naturezas. Parcelas entram no realizado no mês do vencimento.</div>`;},
cards(){const cards=rec('card'),purchases=rec('purchase');return header('Cartões','Compras, parcelas e vencimentos organizados.','new-card','Novo cartão')+`<div class="goal-grid">${cards.map(c=>{const due=purchases.filter(p=>p.cardId===c.id).flatMap(p=>F.schedule(p)).filter(x=>x.date.startsWith(period)).reduce((a,x)=>a+x.amount,0);return `<div class="goal-card"><div class="panel-head"><h2>${esc(c.name)}</h2>${icon('card',23)}</div><span class="tiny muted">COMPROMISSO DO MÊS</span><div class="goal-money">${BRL(due)}</div><div class="goal-meta"><span>Fechamento: ${c.closing||'configurar'}</span><span>Vencimento: ${c.due||'configurar'}</span></div><p class="tiny">Limite informado: ${BRL(c.limit)}${c.bestDay?' · Melhor dia na origem: '+esc(c.bestDay):''}</p><div class="row">${button('Nova compra','new-purchase',`data-card="${c.id}"`,'primary small')}${actions(c)}</div></div>`;}).join('')}</div>${cards.length?'':`<section class="panel">${empty('Nenhum cartão cadastrado','Cadastre o cartão e configure os dias de fechamento e vencimento.','new-card','Adicionar cartão')}</section>`}<div class="split-banner"><div><h2>Compras parceladas</h2><p class="tiny">O resíduo de centavos é distribuído nas primeiras parcelas.</p></div>${cards.length?button('Nova compra','new-purchase','','primary'):''}</div><section class="panel">${purchases.length?table(['Compra','Cartão','Total','Parcelas','1º vencimento',''],purchases.map(p=>`<tr><td class="description">${esc(p.name)}</td><td>${esc(byId(p.cardId)?.name)}</td><td class="money">${BRL(p.amount)}</td><td>${p.count}×</td><td>${dateBR(p.firstDue)}</td><td class="actions">${button('Parcelas','schedule',`data-id="${p.id}"`,'small flat')}${actions(p)}</td></tr>`)):empty('Sem compras registradas','As parcelas são geradas automaticamente, inclusive quando atravessam o ano.','','')}</section><div class="notice">A compra conta uma única vez por parcela no mês de vencimento. Registre a quitação usando a natureza “Pagamento de fatura”, que não acrescenta outra despesa. O primeiro vencimento pode ser ajustado no cadastro da compra.</div>`;},
debts(){const debts=rec('debt'),payments=rec('payment');return header('Dívidas','Acompanhe o que já foi pago e o saldo a quitar.','new-debt','Nova dívida')+`<section class="panel">${debts.length?table(['Credor','Parcela','Total contratado','Pago','Saldo',''],debts.map(d=>{const paid=d.installment*d.paidBefore+payments.filter(p=>p.debtId===d.id).reduce((a,x)=>a+x.amount,0);return `<tr><td>${esc(d.name)}</td><td>${BRL(d.installment)} × ${d.count}</td><td>${BRL(d.installment*d.count)}</td><td>${BRL(paid)}</td><td>${BRL(d.installment*d.count-paid)}</td><td class="actions">${button('Pagar','new-payment',`data-debt="${d.id}"`,'small primary')}${actions(d)}</td></tr>`;})):empty('Nenhuma dívida cadastrada','Registre valores e parcelas para acompanhar a quitação.','new-debt','Adicionar dívida')}</section><section class="panel"><h2>Histórico de pagamentos</h2>${payments.length?table(['Data','Credor','Valor',''],payments.map(p=>`<tr><td>${dateBR(p.date)}</td><td>${esc(byId(p.debtId)?.name)}</td><td>${BRL(p.amount)}</td><td class="actions">${actions(p)}</td></tr>`)):empty('Sem pagamentos','Ao registrar um pagamento aqui, uma saída vinculada será criada em Lançamentos.','','')}</section><div class="notice">Saldo = valor da parcela × quantidade contratada − pagamentos anteriores − pagamentos registrados. Juros e CET são dados informativos; não há capitalização automática.</div>`;},
goals(){const goals=rec('goal');return header('Metas financeiras','Transforme objetivos em próximos passos.','new-goal','Nova meta')+`<div class="goal-grid">${goals.map(g=>{const p=F.goalProgress(g,state.records,today());return `<section class="goal-card"><div class="panel-head"><div><h2>${esc(g.name)}</h2><span class="tiny muted">${esc(g.reason||'Seu próximo objetivo')}</span></div>${icon('target',24)}</div><div class="goal-money">${BRL(p.accumulated)} <small>de ${BRL(g.target)}</small></div>${progress(p.percent)}<div class="goal-meta"><span>${num(p.percent)}% conquistado</span><span>${dateBR(g.deadline)}</span></div><p class="tiny">Faltam ${BRL(p.remaining)} · ${p.monthly!==null?BRL(p.monthly)+' / mês pela regra de 30 dias':p.days!==null&&p.days<=0?'Prazo encerrado':'Defina o prazo para calcular o aporte'}${g.account?'<br>Conta: '+esc(g.account):''}</p><div class="row">${button('Adicionar aporte','new-contribution',`data-goal="${g.id}"`,'primary small')}${actions(g)}</div></section>`;}).join('')}</div>${goals.length?'':`<section class="panel">${empty('Qual é a sua próxima conquista?','Cadastre um objetivo, o valor necessário e uma data.','new-goal','Criar meta')}</section>`}<div class="notice">Aportes atualizam o progresso da meta. Registre a movimentação em Lançamentos apenas se ela ainda não estiver contabilizada. Valores importados podem incluir aportes planejados: confira as datas e o histórico.</div><section class="panel"><h2>Histórico de aportes</h2>${rec('contribution').length?table(['Data / competência','Meta','Valor',''],rec('contribution').sort((a,b)=>b.date.localeCompare(a.date)).map(c=>`<tr><td>${c.periodOnly?c.date.slice(0,7).split('-').reverse().join('/')+' · mês':dateBR(c.date)}</td><td>${esc(byId(c.goalId)?.name)}</td><td>${BRL(c.amount)}</td><td class="actions">${actions(c)}</td></tr>`)):empty('Ainda sem aportes','O valor inicial informado na meta aparece no progresso.','','')}</section>`;},
reserve(){const s=state.settings.reserve,r=F.reserve(s),g=byId(s.goalId),acc=g?F.goalProgress(g,state.records,today()).accumulated:s.accumulated;return header('Reserva ideal','A regra da sua planilha, com acompanhamento do progresso.')+`<div class="equal-col"><section class="panel"><h2>Seu contexto</h2><p class="tiny">Cada resposta determina 3 ou 12 meses. O resultado é a média dos três critérios.</p><form id="reserve-form">${checkField('employed','Tenho carteira assinada',s.employed)}${checkField('children','Tenho filhos',s.children)}${checkField('support','Tenho a quem recorrer em uma emergência',s.support)}${inputField('cost','Gastos fixos mensais (R$)','money',s.cost)}${inputField('accumulated','Valor acumulado manual (R$)','money',s.accumulated)}${selectField('goalId','Ou acompanhar por uma meta',[['','Usar valor manual'],...rec('goal').map(g=>[g.id,g.name])],s.goalId)}<div id="form-error"></div><button class="primary" type="submit">Salvar reserva</button></form></section><section class="panel"><div class="eyebrow">SUA RESERVA DE SEGURANÇA</div><div class="big-result">${BRL(r.target)}</div><p>Equivalente a <strong class="positive">${num(r.months)} meses</strong> dos seus gastos fixos.</p><div class="balance-block"><div class="bar-label"><span>Já acumulado</span><strong>${BRL(acc)}</strong></div>${progress(r.target?acc/r.target*100:0)}<div class="goal-meta"><span>${r.target?num(acc/r.target*100):0}% do objetivo</span><span>Faltam ${BRL(Math.max(0,r.target-acc))}</span></div></div><div class="notice">Fórmula da origem: média dos critérios × gasto fixo mensal. O vínculo com uma meta usa seus aportes sem somar novamente o valor manual.</div></section></div>`;},
simulator(){const s=state.settings.simulator,values=s.bps.every(x=>x===0)?[0,0,0]:F.allocate(s.income,s.bps);return header('Simulação do método','Distribua sua renda com percentuais ajustáveis.')+`<div class="equal-col"><section class="panel"><h2>Defina sua divisão</h2><p class="tiny">Preencha seus percentuais. Eles precisam somar 100%.</p><form id="simulator-form">${inputField('income','Renda mensal (R$)','money',s.income)}${['Essenciais','Estilo de vida','Investimentos'].map((label,i)=>inputField('bps'+i,label+' (%)','percent',s.bps[i]/100)).join('')}<div id="form-error"></div><button type="submit" class="primary">Salvar e calcular</button></form></section><section class="panel"><h2>Seu plano mensal</h2>${values.map((v,i)=>`<div class="bar-row"><div class="bar-label"><span>${['Essenciais','Estilo de vida','Investimentos'][i]} · ${num(s.bps[i]/100)}%</span><strong>${BRL(v)}</strong></div>${progress(s.bps[i]/100)}</div>`).join('')}<div class="balance-block"><div class="bar-label"><span>Total distribuído</span><strong>${BRL(s.income)}</strong></div></div><div class="notice">A divisão entre essenciais, estilo de vida e investimentos segue a estrutura da planilha. Defina seus próprios percentuais. A simulação não cria lançamentos.</div></section></div>`;},
assets(){const assets=rec('asset').filter(a=>a.date.startsWith(period)),total=assets.reduce((a,x)=>a+x.amount,0);return header('Patrimônio','Registre a posição dos seus bens e investimentos em cada mês.','new-asset','Adicionar posição')+`<div class="cards">${stat('Total no mês',total,'Soma das posições informadas','chart',true)}</div><section class="panel">${assets.length?table(['Bem ou investimento','Grupo','Data','Valor',''],assets.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.group)}</td><td>${dateBR(a.date)}</td><td>${BRL(a.amount)}</td><td class="actions">${actions(a)}</td></tr>`)):empty('Nenhuma posição neste mês','Informe o valor de cada bem ou investimento. As posições não criam receitas ou despesas.','new-asset','Adicionar posição')}</section>`;},
achievements(){const a=rec('achievement');return header('Escada da conquista','Pequenos hábitos. Mudanças que ficam.','new-achievement','Novo marco')+`<section class="panel"><div class="bar-label"><span>${a.filter(x=>x.done).length} de ${a.length} marcos conquistados</span><span>${a.length?Math.round(a.filter(x=>x.done).length/a.length*100):0}%</span></div>${progress(a.length?a.filter(x=>x.done).length/a.length*100:0)}</section><div class="steps">${a.map((x,i)=>`<div class="step ${x.done?'done':''}"><div class="num">${x.done?icon('check'):String(i+1).padStart(2,'0')}</div><div class="step-text"><h3>${esc(x.name)}</h3><span class="tiny muted">${x.done?'Conquistado':'Um próximo passo possível'}</span></div>${button(x.done?'Reabrir':'Conquistei','toggle-achievement',`data-id="${x.id}"`,x.done?'small':'small primary')}${actions(x)}</div>`).join('')}</div>${a.length?'':empty('Sua jornada começa agora','Crie um marco ou importe os sete marcos da planilha.','new-achievement','Criar marco')}`;},
wishes(){return genericList('wish','Lista de desejos','Dê tempo e prioridade às suas próximas compras.',['Item','Valor','Necessidade','Prioridade','Quando'],w=>[esc(w.name),BRL(w.amount),esc(w.need),w.priority,dateBR(w.date)]);},
bills(){return genericList('bill','Contas a pagar','Um lembrete mensal, separado dos lançamentos efetivamente registrados.',['Conta','Vencimento','Valor','Situação'],b=>[esc(b.name),dateBR(b.date),BRL(b.amount),b.paid?'Paga':'Em aberto'],r=>r.date.startsWith(period));},
categories(){return header('Categorias','Organize receitas e despesas preservando o histórico.','new-category','Nova categoria')+`<section class="panel">${rec('category').length?table(['Nome','Grupo','Natureza','Situação',''],rec('category').map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${F.TYPES[c.type]}</td><td>${c.archived?'Arquivada':'Ativa'}</td><td class="actions">${actions(c)}</td></tr>`)):empty('Organize do seu jeito','Crie categorias ou importe as categorias da planilha.','new-category','Criar categoria')}</section><div class="notice">Categorias utilizadas não podem ser excluídas. Arquive para ocultar dos novos lançamentos. Alterar o nome mantém todos os vínculos; a natureza de uma categoria utilizada permanece fixa.</div>`;},
import(){return header('Importar sua planilha','Confira antes de gravar. O arquivo original permanece intacto.')+`<section class="panel"><div class="panel-head"><div><h2>1. Selecione a referência</h2><p class="tiny">XLSX do Painel Financeiro ou cópia de células do Google em JSON.</p></div>${button('Selecionar arquivo','choose-import','','primary')}</div><div class="file-name">${chosenFile?esc(chosenFile):'Nenhum arquivo selecionado'}</div></section><section class="panel"><h2>2. Defina como interpretar os dados</h2><form id="import-form"><div class="form-grid">${inputField('importYear','Ano dos lançamentos e aportes','number',importOptions.year)}${selectField('cardSource','Fonte das despesas de cartão',[['monthly','Lançamentos mensais (regra da origem)'],['detailed','Parcelas do Controle de Cartões']],importOptions.cardSource)}</div>${checkField('useGoalList','Completar metas pelo valor e prazo da lista superior. Prazo mensal será o último dia do mês.',importOptions.useGoalList)}<p class="tiny">Títulos com “2024” são antigos e não determinam o ano. Aportes sem dia usam o dia 01 apenas como competência. Na fonte mensal, compras detalhadas ficam na revisão; na fonte de parcelas, pagamentos de fatura não contam novamente.</p><div id="form-error"></div><button class="primary" type="submit" ${!chosenFile||busy?'disabled':''}>${busy?'Lendo planilha…':'Conferir importação'}</button></form></section>${importPlan?importReview():''}<div class="notice">A importação desta versão exige uma base vazia, evitando sobreposição e duplicação de metas, saldos e categorias. O mesmo arquivo não pode ser importado novamente. Faça backup antes de trocar de base.</div>`;},
settings(){return header('Dados e preferências','Seu histórico fica neste computador, sob seu controle.')+`<div class="equal-col"><section class="panel"><h2>Proteção dos dados</h2><p>Backup automático ao abrir, com as últimas 14 datas preservadas. Antes de restaurar, uma cópia adicional protege os dados atuais.</p><div class="row">${button('Exportar backup','backup','','primary')}${button('Restaurar backup','restore')}</div><div class="notice">Ao atualizar, substitua os arquivos do programa e preserve a pasta <strong>dados</strong>.</div><h3>Backups disponíveis</h3><ul class="info-list">${state.backups.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Nenhum backup automático.</li>'}</ul></section><section class="panel"><h2>Armazenamento local</h2><p class="path">${esc(state.dataPath)}</p>${button('Abrir pasta de dados','open-data')}<div class="balance-block"><h3>Aparência</h3><p class="tiny">Tema atual: ${state.settings.theme==='light'?'claro':'escuro'}</p>${button('Alternar tema','theme')}</div><p class="export-note">Sem conta, telemetria ou sincronização. Todas as funções principais operam offline.</p></section></div><section class="panel"><h2>Importações realizadas</h2>${state.imports.length?state.imports.map(i=>`<div class="notice"><strong>${esc(i.name)}</strong> · ano ${i.year}<br>${esc(i.date)}<ul>${i.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`).join(''):empty('Nenhuma importação','O relatório de conferência será preservado junto dos dados.','','')}</section>`;}
};
function normText(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function genericList(kind,title,sub,headers,mapper,predicate=()=>true){const records=rec(kind).filter(predicate);return header(title,sub,'new-'+kind,'Adicionar')+`<section class="panel">${records.length?table([...headers,''],records.map(r=>`<tr>${mapper(r).map(c=>`<td>${c}</td>`).join('')}<td class="actions">${actions(r)}</td></tr>`)):empty('Ainda sem registros','Adicione o primeiro item para começar.','new-'+kind,'Adicionar')}</section>`;}
function importReview(){const p=importPlan;const labels={category:'Categorias',goal:'Metas',contribution:'Aportes',card:'Cartões',achievement:'Marcos',entry:'Lançamentos',budget:'Orçamentos',debt:'Dívidas',asset:'Posições',purchase:'Compras',wish:'Desejos',bill:'Contas'};return `<section class="panel"><h2>3. Confira os dados</h2><div class="toolbar">${Object.entries(p.counts).map(([k,n])=>`<span class="tag">${labels[k]||k}: ${n}</span>`).join('')}</div><h3>Regras e observações</h3><ul class="info-list">${p.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul><h3>Conferência de totais</h3>${table(['Origem','Valor na planilha','Valor importado'],p.checks.map(c=>`<tr><td>${esc(c.sheet)}</td><td>${BRL(Math.round((c.sourceIncome??c.sourceTarget??c.sourceTotal??0)*100))}${c.sourceOut!==undefined?' / saídas '+BRL(Math.round(c.sourceOut*100)):''}</td><td>${BRL(Math.round((c.importIncome??c.importTarget??c.importTotal??0)*100))}${c.importOut!==undefined?' / saídas '+BRL(Math.round(c.importOut*100)):''}</td></tr>`))}${p.issues.length?`<div class="notice warn"><h3>${p.issues.length} itens precisam de revisão e não serão gravados</h3><ul>${p.issues.map(i=>`<li><strong>${esc(i.source)}</strong>: ${esc(i.message)}<br><span class="tiny">${esc(JSON.stringify(i.raw))}</span></li>`).join('')}</ul>Corrija o arquivo e confira novamente, ou exclua explicitamente esses itens desta importação. O relatório mantém os valores originais.</div>${checkField('acceptSkipped','Autorizo importar sem os itens listados acima; vou revisá-los pelo relatório.',false)}`:''}${checkField('confirmImport',`Conferi o ano ${p.year}, os totais e as regras acima.`,false)}${button('Confirmar e importar','commit-import','','primary')}</section>`;}
function inputField(name,label,type,value,required=true){let val=value??'';if(type==='money')val=(Number(val||0)/100).toFixed(2).replace('.',',');return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${['money','percent'].includes(type)?'text':type}" ${type==='money'?'inputmode="decimal"':''} value="${esc(val)}" ${required?'required':''} ${type==='number'?'step="1"':''}><span class="field-error" data-error="${name}"></span></div>`;}
function selectField(name,label,options,value){return `<div class="field"><label for="${name}">${label}</label><select name="${name}" id="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`;}
function checkField(name,label,checked){return `<div class="check"><input type="checkbox" id="${name}" name="${name}" ${checked?'checked':''}><label for="${name}">${label}</label></div>`;}
const field=(key,label,type='text',extra={})=>({key,label,type,...extra});
function schema(kind,r){const categories=rec('category').filter(c=>!c.archived||c.id===r.categoryId);const options=kind==='purchase'?categories.filter(c=>c.type==='despesa'):categories;const catField=field('categoryId','Categoria','select',{options:[['','Selecione…'],...options.map(c=>[c.id,c.name+' · '+F.TYPES[c.type]])]});const money=(key,label)=>field(key,label,'money');const date=field('date','Data','date');const name=field('name','Nome');const schemas={
category:[name,field('group','Grupo'),field('type','Natureza','select',{options:Object.entries(F.TYPES).filter(([k])=>k!=='transferencia')}),field('archived','Arquivar categoria','check')],
entry:[field('description','Descrição'),date,field('type','Natureza','select',{options:Object.entries(F.TYPES)}),catField,money('amount','Valor (R$)')],
budget:[catField,field('period','Mês e ano','month'),money('amount','Valor previsto (R$)')],
card:[name,field('closing','Dia de fechamento (1 a 31)','number'),field('due','Dia de vencimento (1 a 31)','number'),money('limit','Limite (R$)')],
purchase:[name,field('cardId','Cartão','select',{options:rec('card').map(c=>[c.id,c.name])}),catField,date,money('amount','Valor total (R$)'),field('firstDue','Vencimento da parcela atual','date'),field('currentInstallment','Parcela atual','number'),field('count','Quantidade de parcelas','number')],
debt:[name,date,money('installment','Valor da parcela (R$)'),field('count','Quantidade contratada','number'),field('paidBefore','Quantidade já paga antes do cadastro','number'),field('interest','Juros informados','text',{optional:true}),field('cet','CET informado','text',{optional:true}),field('reason','Motivo','text',{optional:true})],
payment:[field('debtId','Dívida','select',{options:rec('debt').map(d=>[d.id,d.name])}),date,money('amount','Valor pago (R$)')],
goal:[name,money('target','Valor da meta (R$)'),money('initial','Valor inicial (R$)'),field('deadline','Prazo','date',{optional:true}),field('reason','Motivo','text',{optional:true}),field('account','Banco ou conta','text',{optional:true})],
contribution:[field('goalId','Meta','select',{options:rec('goal').map(g=>[g.id,g.name])}),date,money('amount','Aporte (R$)')],
asset:[name,field('group','Grupo'),date,money('amount','Valor da posição (R$)')],
achievement:[name,field('done','Já conquistei este marco','check')],
wish:[name,money('amount','Quanto custa? (R$)'),field('need','Preciso ou quero?','select',{options:[['Preciso','Preciso'],['Quero','Quero']]}),field('urgency','Agora ou posso esperar?','select',{options:[['Posso esperar','Posso esperar'],['Agora','Agora']]}),field('priority','Prioridade (1 a 5)','number'),field('date','Quando?','date',{optional:true})],
bill:[name,catField,date,money('amount','Valor (R$)'),field('paid','Conta paga (controle de lembrete)','check')]
};return schemas[kind];}
function modal(content){const d=$('#modal');d.innerHTML=content;if(!d.open)d.showModal();d.querySelector('input:not([type=checkbox]),select')?.focus();}
function enableCategoryCreation(form,kind){
 const select=form.elements.categoryId;if(!select)return;
 const createValue='__new_category__';select.add(new Option('+ Adicionar nova categoria',createValue));
 let previous=select.value;
 select.addEventListener('change',()=>{
  if(select.value!==createValue){previous=select.value;return;}
  select.value=previous;
  const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','quick-category-title');
  const types=Object.entries(F.TYPES).filter(([key])=>key!=='transferencia'&&(kind!=='purchase'||key==='despesa'));
  const preferred=form.elements.type?.value||'despesa';
  dialog.innerHTML=`<div class="dialog-heading"><h2 id="quick-category-title">Adicionar nova categoria</h2><button type="button" class="flat" data-dismiss-category aria-label="Fechar">×</button></div><form><div class="form-grid">${inputField('quick-category-name','Nome','text','')}${inputField('quick-category-group','Grupo','text','Outros')}${selectField('quick-category-type','Natureza',types,types.some(([key])=>key===preferred)?preferred:'despesa')}</div><div class="quick-category-error" role="alert"></div><div class="dialog-footer"><button type="button" data-dismiss-category>Cancelar</button><button type="submit" class="primary">Salvar categoria</button></div></form>`;
  document.body.append(dialog);
  let saving=false;
  dialog.querySelectorAll('[data-dismiss-category]').forEach(button=>button.addEventListener('click',()=>{if(!saving)dialog.close();}));
  dialog.addEventListener('cancel',event=>{if(saving)event.preventDefault();});
  dialog.addEventListener('close',()=>{dialog.remove();select.focus();},{once:true});
  dialog.querySelector('form').addEventListener('submit',async event=>{
   event.preventDefault();event.stopPropagation();if(saving)return;
   const fields=event.currentTarget.elements;
   const buttons=dialog.querySelectorAll('button');saving=true;buttons.forEach(button=>button.disabled=true);
   try{
    const category=await api('save',{kind:'category',name:fields['quick-category-name'].value.trim(),group:fields['quick-category-group'].value.trim(),type:fields['quick-category-type'].value,archived:false});
    state.records.push(category);
    select.add(new Option(category.name+' · '+F.TYPES[category.type],category.id),select.options[select.options.length-1]);
    select.value=category.id;select.dispatchEvent(new Event('change',{bubbles:true}));
    dialog.close();toast('Categoria criada e selecionada.');
   }catch(error){dialog.querySelector('.quick-category-error').innerHTML=`<div class="form-error">${esc(error.message)}</div>`;}
   finally{saving=false;buttons.forEach(button=>button.disabled=false);}
  });
  dialog.showModal();dialog.querySelector('input').focus();
 });
}
function openForm(kind,existing={},presets={}){const r={kind,date:period+'-'+(today().startsWith(period)?today().slice(8):'01'),period,type:'despesa',group:'Outros',amount:0,target:0,initial:0,limit:0,count:1,currentInstallment:1,paidBefore:0,priority:3,closing:0,due:0,...presets,...existing};const fields=schema(kind,r);if(!fields)throw Error('Formulário indisponível.');const titles={entry:'lançamento',category:'categoria',budget:'orçamento',card:'cartão',purchase:'compra',debt:'dívida',payment:'pagamento',goal:'meta',contribution:'aporte',asset:'posição',achievement:'marco',wish:'desejo',bill:'conta'};
modal(`<div class="dialog-heading"><h2>${r.id?'Editar':'Adicionar'} ${titles[kind]}</h2>${button('×','close-modal','aria-label="Fechar"','flat')}</div><form id="entity-form"><div class="form-grid">${fields.map(f=>f.type==='select'?selectField(f.key,f.label,f.options,r[f.key]):f.type==='check'?checkField(f.key,f.label,r[f.key]):inputField(f.key,f.label,f.type,r[f.key],!f.optional)).join('')}</div>${kind==='purchase'?'<p class="tiny">Compras após o fechamento entram na próxima fatura. No dia do fechamento entram na fatura atual. Informe o valor total original da compra e o vencimento da parcela atual. Somente a parcela atual e as seguintes serão cadastradas; as anteriores não serão lançadas nem marcadas como pagas.</p>':''}${r.schedule?'<div class="notice">Esta compra tem distribuição mensal importada. Para alterar o total ou as parcelas, exclua e cadastre novamente; o cronograma da origem será preservado ao editar o nome.</div>':''}<div id="entity-error"></div><div class="dialog-footer">${button('Cancelar','close-modal')}<button class="primary" type="submit">Salvar ${titles[kind]}</button></div></form>`);
const form=$('#entity-form');form.addEventListener('submit',async e=>{e.preventDefault();const out={...r};try{for(const f of fields){const input=form.elements[f.key];try{out[f.key]=f.type==='check'?input.checked:f.type==='money'?F.money(input.value):f.type==='number'?Number(input.value):input.value.trim();}catch(error){form.querySelector(`[data-error="${f.key}"]`).textContent=error.message;input.focus();throw error;}}if(kind==='entry'&&out.type==='transferencia')out.categoryId='';if(kind==='contribution')out.periodOnly=false;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await api('save',out);}finally{submit.disabled=false;}$('#modal').close();await refresh();toast('Registro salvo.');}catch(err){$('#entity-error').innerHTML=`<div class="form-error" role="alert">${esc(err.message)}</div>`;}});
if(kind==='entry'){const category=form.elements.categoryId;category.addEventListener('change',()=>{const c=byId(category.value);if(c)form.elements.type.value=c.type;});}
enableCategoryCreation(form,kind);
if(kind==='purchase'){const current=form.elements.currentInstallment,total=form.elements.count;total.min='1';total.max='600';total.step='1';current.min='1';current.step='1';const bounds=()=>{current.max=total.value;current.setCustomValidity(Number.isInteger(Number(current.value))&&Number(current.value)>=1&&Number(current.value)<=Number(total.value)?'':'A parcela atual deve estar entre 1 e a quantidade de parcelas.');};total.addEventListener('input',bounds);current.addEventListener('input',bounds);bounds();if(r.schedule){for(const key of ['currentInstallment','count','amount','firstDue'])form.elements[key].readOnly=true;}const calculate=()=>{const card=byId(form.elements.cardId.value);if(card?.closing&&card?.due&&F.validDate(form.elements.date.value))form.elements.firstDue.value=F.firstDue(form.elements.date.value,card.closing,card.due);};form.elements.date.addEventListener('change',calculate);form.elements.cardId.addEventListener('change',calculate);if(!r.firstDue)calculate();}
}
async function doAction(action,el){const id=el?.dataset.id;switch(action){case 'navigate':route=el.dataset.route;query='';filter='';page=0;render();return;case 'navigate-import':route='import';render();return;case 'collapse':document.body.classList.toggle('collapsed');return;case 'theme':await api('setting',{key:'theme',value:state.settings.theme==='dark'?'light':'dark'});await refresh();return;case 'close-modal':$('#modal').close();return;case 'edit':{const r=byId(id);openForm(r.kind,r);return;}case 'delete':{const r=byId(id);modal(`<h2>Excluir este registro?</h2><p>${esc(r.name||r.description||'Registro de '+r.kind)}. Esta ação remove o registro salvo.</p><div id="delete-error"></div><div class="dialog-footer">${button('Cancelar','close-modal')}${button('Excluir registro','confirm-delete',`data-id="${id}"`,'danger')}</div>`);return;}case 'confirm-delete':try{await api('remove',{id});$('#modal').close();await refresh();toast('Registro excluído.');}catch(e){$('#delete-error').innerHTML=`<div class="form-error">${esc(e.message)}</div>`;}return;
case 'toggle-achievement':{const r=byId(id);await api('save',{...r,done:!r.done});await refresh();return;}
case 'schedule':{const p=byId(id);modal(`<div class="dialog-heading"><h2>${esc(p.name)} · parcelas</h2>${button('×','close-modal','aria-label="Fechar"','flat')}</div>${table(['Parcela','Vencimento','Valor'],F.schedule(p).map((x,i)=>`<tr><td>${x.number??i+1} / ${p.count}</td><td>${dateBR(x.date)}</td><td>${BRL(x.amount)}</td></tr>`))}`);return;}
case 'choose-import':{const chosen=await api('chooseImport');if(chosen){chosenFile=chosen;importPlan=null;render();}return;}
case 'commit-import':await api('import',{confirm:$('#confirmImport').checked,acceptSkipped:$('#acceptSkipped')?.checked||false});importPlan=null;chosenFile='';await refresh();toast('Importação concluída e salva.');return;
case 'backup':{const p=await api('backup');if(p)toast('Backup salvo em '+p);await refresh();return;}
case 'restore':{const ok=await api('restore');if(ok){await refresh();toast('Backup restaurado.');}return;}
case 'open-data':await api('openData');return;case 'csv':{const p=await api('csv',{period});if(p)toast('CSV salvo em '+p);return;}
case 'prev-page':page=Math.max(0,page-1);render();return;case 'next-page':page++;render();return;
default:if(action.startsWith('new-')){const kind=action.slice(4),presets={};if(el?.dataset.category)presets.categoryId=el.dataset.category;if(el?.dataset.card)presets.cardId=el.dataset.card;if(el?.dataset.goal)presets.goalId=el.dataset.goal;if(el?.dataset.debt){presets.debtId=el.dataset.debt;presets.amount=byId(presets.debtId).installment;}openForm(kind,{},presets);return;}throw Error('Ação indisponível.');}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();Promise.resolve(doAction(b.dataset.action,b)).catch(err=>toast(err.message,true));});
document.addEventListener('change',e=>{if(['month','year'].includes(e.target.id)){const year=+$('#year').value,month=+$('#month').value;if(year<1900||year>2200||!Number.isInteger(year)){toast('Informe um ano entre 1900 e 2200.',true);return;}period=`${year}-${String(month).padStart(2,'0')}`;page=0;render();}if(e.target.id==='type-filter'){filter=e.target.value;page=0;render();}if(e.target.id==='sort'){sort=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;const pos=e.target.selectionStart;page=0;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);}});
document.addEventListener('submit',async e=>{if(e.target.id==='entity-form')return;e.preventDefault();const form=e.target;try{if(form.id==='simulator-form'){const income=F.money(form.income.value),bps=[0,1,2].map(i=>F.money(form['bps'+i].value));F.allocate(income,bps);await api('setting',{key:'simulator',value:{income,bps}});await refresh();toast('Simulação salva.');}if(form.id==='reserve-form'){const value={employed:form.employed.checked,children:form.children.checked,support:form.support.checked,cost:F.money(form.cost.value),accumulated:F.money(form.accumulated.value),goalId:form.goalId.value};await api('setting',{key:'reserve',value});await refresh();toast('Reserva atualizada.');}if(form.id==='import-form'){importOptions={year:Number(form.importYear.value),useGoalList:form.useGoalList.checked,cardSource:form.cardSource.value};busy=true;render();try{importPlan=await api('preview',importOptions);}finally{busy=false;render();}toast('Conferência pronta. Revise os valores antes de importar.');}}catch(err){busy=false;const target=$('#form-error');if(target)target.innerHTML=`<div class="form-error" role="alert">${esc(err.message)}</div>`;else toast(err.message,true);}});
window.addEventListener('error',e=>toast('Não foi possível concluir: '+e.message,true));refresh().catch(e=>{$('#app').innerHTML=`<div class="content"><h1>Não foi possível abrir seus dados</h1><p>${esc(e.message)}</p></div>`;});
